/*
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.moysklad.remap_1_2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.moysklad.remap_1_2.model.Account;
import ru.moysklad.remap_1_2.model.Agent;
import ru.moysklad.remap_1_2.model.AttributeAbstract;
import ru.moysklad.remap_1_2.model.Contract;
import ru.moysklad.remap_1_2.model.CurrencyRate;
import ru.moysklad.remap_1_2.model.Employee;
import ru.moysklad.remap_1_2.model.Error;
import ru.moysklad.remap_1_2.model.ErrorErrorsInner;
import ru.moysklad.remap_1_2.model.FileList;
import ru.moysklad.remap_1_2.model.Group;
import ru.moysklad.remap_1_2.model.InvoiceIn;
import ru.moysklad.remap_1_2.model.InvoiceInPositionList;
import ru.moysklad.remap_1_2.model.Meta;
import ru.moysklad.remap_1_2.model.Organization;
import ru.moysklad.remap_1_2.model.Project;
import ru.moysklad.remap_1_2.model.PurchaseOrder;
import ru.moysklad.remap_1_2.model.SalesReturnPaymentsInner;
import ru.moysklad.remap_1_2.model.State;
import ru.moysklad.remap_1_2.model.Store;
import ru.moysklad.remap_1_2.model.Supply;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * CreateInvoiceInBatch200ResponseInner
 */
@JsonPropertyOrder({
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_META,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_ID,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_ACCOUNT_ID,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_NAME,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_CODE,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_EXTERNAL_CODE,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_SYNC_ID,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_DESCRIPTION,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_CREATED,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_DELETED,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_UPDATED,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_MOMENT,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_PAYMENT_PLANNED_MOMENT,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_INCOMING_DATE,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_INCOMING_NUMBER,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_APPLICABLE,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_PRINTED,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_PUBLISHED,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_SHARED,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_VAT_ENABLED,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_VAT_INCLUDED,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_VAT_SUM,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_SUM,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_PAYED_SUM,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_SHIPPED_SUM,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_ORGANIZATION,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_ORGANIZATION_ACCOUNT,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_AGENT,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_AGENT_ACCOUNT,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_STORE,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_STATE,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_CONTRACT,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_PROJECT,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_OWNER,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_GROUP,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_ATTRIBUTES,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_FILES,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_RATE,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_POSITIONS,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_PURCHASE_ORDER,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_SUPPLIES,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_PAYMENTS,
  CreateInvoiceInBatch200ResponseInner.JSON_PROPERTY_ERRORS
})
@JsonTypeName("createInvoiceInBatch_200_response_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-10T08:38:11.949143335Z[GMT]", comments = "Generator version: 7.14.0")
public class CreateInvoiceInBatch200ResponseInner {

  public static final String JSON_PROPERTY_META = "meta";
  @javax.annotation.Nullable
  private Meta meta;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @javax.annotation.Nullable
  private UUID accountId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nullable
  private String code;

  public static final String JSON_PROPERTY_EXTERNAL_CODE = "externalCode";
  @javax.annotation.Nullable
  private String externalCode;

  public static final String JSON_PROPERTY_SYNC_ID = "syncId";
  @javax.annotation.Nullable
  private UUID syncId;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  @javax.annotation.Nullable
  private String deleted;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  @javax.annotation.Nullable
  private String updated;

  public static final String JSON_PROPERTY_MOMENT = "moment";
  @javax.annotation.Nullable
  private String moment;

  public static final String JSON_PROPERTY_PAYMENT_PLANNED_MOMENT = "paymentPlannedMoment";
  @javax.annotation.Nullable
  private String paymentPlannedMoment;

  public static final String JSON_PROPERTY_INCOMING_DATE = "incomingDate";
  @javax.annotation.Nullable
  private JsonNullable<String> incomingDate = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_INCOMING_NUMBER = "incomingNumber";
  @javax.annotation.Nullable
  private JsonNullable<String> incomingNumber = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_APPLICABLE = "applicable";
  @javax.annotation.Nullable
  private Boolean applicable;

  public static final String JSON_PROPERTY_PRINTED = "printed";
  @javax.annotation.Nullable
  private Boolean printed;

  public static final String JSON_PROPERTY_PUBLISHED = "published";
  @javax.annotation.Nullable
  private Boolean published;

  public static final String JSON_PROPERTY_SHARED = "shared";
  @javax.annotation.Nullable
  private Boolean shared;

  public static final String JSON_PROPERTY_VAT_ENABLED = "vatEnabled";
  @javax.annotation.Nullable
  private Boolean vatEnabled;

  public static final String JSON_PROPERTY_VAT_INCLUDED = "vatIncluded";
  @javax.annotation.Nullable
  private Boolean vatIncluded;

  public static final String JSON_PROPERTY_VAT_SUM = "vatSum";
  @javax.annotation.Nullable
  private Double vatSum;

  public static final String JSON_PROPERTY_SUM = "sum";
  @javax.annotation.Nullable
  private Double sum;

  public static final String JSON_PROPERTY_PAYED_SUM = "payedSum";
  @javax.annotation.Nullable
  private Double payedSum;

  public static final String JSON_PROPERTY_SHIPPED_SUM = "shippedSum";
  @javax.annotation.Nullable
  private Double shippedSum;

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  @javax.annotation.Nullable
  private Organization organization;

  public static final String JSON_PROPERTY_ORGANIZATION_ACCOUNT = "organizationAccount";
  @javax.annotation.Nullable
  private JsonNullable<Account> organizationAccount = JsonNullable.<Account>undefined();

  public static final String JSON_PROPERTY_AGENT = "agent";
  @javax.annotation.Nullable
  private Agent agent;

  public static final String JSON_PROPERTY_AGENT_ACCOUNT = "agentAccount";
  @javax.annotation.Nullable
  private JsonNullable<Account> agentAccount = JsonNullable.<Account>undefined();

  public static final String JSON_PROPERTY_STORE = "store";
  @javax.annotation.Nullable
  private JsonNullable<Store> store = JsonNullable.<Store>undefined();

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private JsonNullable<State> state = JsonNullable.<State>undefined();

  public static final String JSON_PROPERTY_CONTRACT = "contract";
  @javax.annotation.Nullable
  private JsonNullable<Contract> contract = JsonNullable.<Contract>undefined();

  public static final String JSON_PROPERTY_PROJECT = "project";
  @javax.annotation.Nullable
  private JsonNullable<Project> project = JsonNullable.<Project>undefined();

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private JsonNullable<Employee> owner = JsonNullable.<Employee>undefined();

  public static final String JSON_PROPERTY_GROUP = "group";
  @javax.annotation.Nullable
  private Group group;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  @javax.annotation.Nullable
  private JsonNullable<List<AttributeAbstract>> attributes = JsonNullable.<List<AttributeAbstract>>undefined();

  public static final String JSON_PROPERTY_FILES = "files";
  @javax.annotation.Nullable
  private JsonNullable<FileList> files = JsonNullable.<FileList>undefined();

  public static final String JSON_PROPERTY_RATE = "rate";
  @javax.annotation.Nullable
  private CurrencyRate rate;

  public static final String JSON_PROPERTY_POSITIONS = "positions";
  @javax.annotation.Nullable
  private InvoiceInPositionList positions;

  public static final String JSON_PROPERTY_PURCHASE_ORDER = "purchaseOrder";
  @javax.annotation.Nullable
  private JsonNullable<PurchaseOrder> purchaseOrder = JsonNullable.<PurchaseOrder>undefined();

  public static final String JSON_PROPERTY_SUPPLIES = "supplies";
  @javax.annotation.Nullable
  private JsonNullable<List<Supply>> supplies = JsonNullable.<List<Supply>>undefined();

  public static final String JSON_PROPERTY_PAYMENTS = "payments";
  @javax.annotation.Nullable
  private JsonNullable<List<SalesReturnPaymentsInner>> payments = JsonNullable.<List<SalesReturnPaymentsInner>>undefined();

  public static final String JSON_PROPERTY_ERRORS = "errors";
  @javax.annotation.Nonnull
  private List<ErrorErrorsInner> errors = new ArrayList<>();

  public CreateInvoiceInBatch200ResponseInner() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public CreateInvoiceInBatch200ResponseInner(
    @JsonProperty(value = JSON_PROPERTY_ID, required = false) UUID id, 
    @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false) UUID accountId, 
    @JsonProperty(value = JSON_PROPERTY_CREATED, required = false) String created, 
    @JsonProperty(value = JSON_PROPERTY_DELETED, required = false) String deleted, 
    @JsonProperty(value = JSON_PROPERTY_UPDATED, required = false) String updated, 
    @JsonProperty(value = JSON_PROPERTY_PRINTED, required = false) Boolean printed, 
    @JsonProperty(value = JSON_PROPERTY_PUBLISHED, required = false) Boolean published, 
    @JsonProperty(value = JSON_PROPERTY_VAT_SUM, required = false) Double vatSum, 
    @JsonProperty(value = JSON_PROPERTY_SUM, required = false) Double sum, 
    @JsonProperty(value = JSON_PROPERTY_PAYED_SUM, required = false) Double payedSum, 
    @JsonProperty(value = JSON_PROPERTY_SHIPPED_SUM, required = false) Double shippedSum
  ) {
    this();
    this.id = id;
    this.accountId = accountId;
    this.created = created;
    this.deleted = deleted;
    this.updated = updated;
    this.printed = printed;
    this.published = published;
    this.vatSum = vatSum;
    this.sum = sum;
    this.payedSum = payedSum;
    this.shippedSum = shippedSum;
  }

  public CreateInvoiceInBatch200ResponseInner meta(@javax.annotation.Nullable Meta meta) {
    
    this.meta = meta;
    return this;
  }


  /**
   * Get meta
   * @return meta
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Meta getMeta() {
    return meta;
  }

  


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@javax.annotation.Nullable Meta meta) {
    this.meta = meta;
  }


  /**
   * ID Счета поставщика
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getId() {
    return id;
  }

  



  /**
   * ID учетной записи
   * @return accountId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getAccountId() {
    return accountId;
  }

  



  public CreateInvoiceInBatch200ResponseInner name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }


  /**
   * Наименование Счета поставщика
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }

  


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CreateInvoiceInBatch200ResponseInner code(@javax.annotation.Nullable String code) {
    
    this.code = code;
    return this;
  }


  /**
   * Код Счета поставщика
   * @return code
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }

  


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public CreateInvoiceInBatch200ResponseInner externalCode(@javax.annotation.Nullable String externalCode) {
    
    this.externalCode = externalCode;
    return this;
  }


  /**
   * Внешний код Счета поставщика
   * @return externalCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalCode() {
    return externalCode;
  }

  


  @JsonProperty(JSON_PROPERTY_EXTERNAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalCode(@javax.annotation.Nullable String externalCode) {
    this.externalCode = externalCode;
  }


  public CreateInvoiceInBatch200ResponseInner syncId(@javax.annotation.Nullable UUID syncId) {
    
    this.syncId = syncId;
    return this;
  }


  /**
   * ID синхронизации
   * @return syncId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYNC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getSyncId() {
    return syncId;
  }

  


  @JsonProperty(JSON_PROPERTY_SYNC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSyncId(@javax.annotation.Nullable UUID syncId) {
    this.syncId = syncId;
  }


  public CreateInvoiceInBatch200ResponseInner description(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }


  /**
   * Комментарий Счета поставщика
   * @return description
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  /**
   * Дата создания
   * @return created
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }

  



  /**
   * Момент последнего удаления Счета поставщика
   * @return deleted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeleted() {
    return deleted;
  }

  



  /**
   * Момент последнего обновления Счета поставщика
   * @return updated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdated() {
    return updated;
  }

  



  public CreateInvoiceInBatch200ResponseInner moment(@javax.annotation.Nullable String moment) {
    
    this.moment = moment;
    return this;
  }


  /**
   * Дата документа
   * @return moment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMoment() {
    return moment;
  }

  


  @JsonProperty(JSON_PROPERTY_MOMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMoment(@javax.annotation.Nullable String moment) {
    this.moment = moment;
  }


  public CreateInvoiceInBatch200ResponseInner paymentPlannedMoment(@javax.annotation.Nullable String paymentPlannedMoment) {
    
    this.paymentPlannedMoment = paymentPlannedMoment;
    return this;
  }


  /**
   * Планируемая дата оплаты
   * @return paymentPlannedMoment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYMENT_PLANNED_MOMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getPaymentPlannedMoment() {
    return paymentPlannedMoment;
  }

  


  @JsonProperty(JSON_PROPERTY_PAYMENT_PLANNED_MOMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentPlannedMoment(@javax.annotation.Nullable String paymentPlannedMoment) {
    this.paymentPlannedMoment = paymentPlannedMoment;
  }


  public CreateInvoiceInBatch200ResponseInner incomingDate(@javax.annotation.Nullable String incomingDate) {
    this.incomingDate = JsonNullable.<String>of(incomingDate);
    
    return this;
  }


  /**
   * Входящая дата
   * @return incomingDate
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getIncomingDate() {
        return incomingDate.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_INCOMING_DATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<String> getIncomingDate_JsonNullable() {
    return incomingDate;
  }
  
  @JsonProperty(value = JSON_PROPERTY_INCOMING_DATE, required = false)
  public void setIncomingDate_JsonNullable(JsonNullable<String> incomingDate) {
    this.incomingDate = incomingDate;
  }

  public void setIncomingDate(@javax.annotation.Nullable String incomingDate) {
    this.incomingDate = JsonNullable.<String>of(incomingDate);
  }


  public CreateInvoiceInBatch200ResponseInner incomingNumber(@javax.annotation.Nullable String incomingNumber) {
    this.incomingNumber = JsonNullable.<String>of(incomingNumber);
    
    return this;
  }


  /**
   * Входящий номер
   * @return incomingNumber
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getIncomingNumber() {
        return incomingNumber.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_INCOMING_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<String> getIncomingNumber_JsonNullable() {
    return incomingNumber;
  }
  
  @JsonProperty(value = JSON_PROPERTY_INCOMING_NUMBER, required = false)
  public void setIncomingNumber_JsonNullable(JsonNullable<String> incomingNumber) {
    this.incomingNumber = incomingNumber;
  }

  public void setIncomingNumber(@javax.annotation.Nullable String incomingNumber) {
    this.incomingNumber = JsonNullable.<String>of(incomingNumber);
  }


  public CreateInvoiceInBatch200ResponseInner applicable(@javax.annotation.Nullable Boolean applicable) {
    
    this.applicable = applicable;
    return this;
  }


  /**
   * Отметка о проведении
   * @return applicable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPLICABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getApplicable() {
    return applicable;
  }

  


  @JsonProperty(JSON_PROPERTY_APPLICABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApplicable(@javax.annotation.Nullable Boolean applicable) {
    this.applicable = applicable;
  }


  /**
   * Напечатан ли документ
   * @return printed
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRINTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPrinted() {
    return printed;
  }

  



  /**
   * Опубликован ли документ
   * @return published
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPublished() {
    return published;
  }

  



  public CreateInvoiceInBatch200ResponseInner shared(@javax.annotation.Nullable Boolean shared) {
    
    this.shared = shared;
    return this;
  }


  /**
   * Общий доступ
   * @return shared
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShared() {
    return shared;
  }

  


  @JsonProperty(JSON_PROPERTY_SHARED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShared(@javax.annotation.Nullable Boolean shared) {
    this.shared = shared;
  }


  public CreateInvoiceInBatch200ResponseInner vatEnabled(@javax.annotation.Nullable Boolean vatEnabled) {
    
    this.vatEnabled = vatEnabled;
    return this;
  }


  /**
   * Учитывается ли НДС
   * @return vatEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVatEnabled() {
    return vatEnabled;
  }

  


  @JsonProperty(JSON_PROPERTY_VAT_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatEnabled(@javax.annotation.Nullable Boolean vatEnabled) {
    this.vatEnabled = vatEnabled;
  }


  public CreateInvoiceInBatch200ResponseInner vatIncluded(@javax.annotation.Nullable Boolean vatIncluded) {
    
    this.vatIncluded = vatIncluded;
    return this;
  }


  /**
   * Включен ли НДС в цену
   * @return vatIncluded
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVatIncluded() {
    return vatIncluded;
  }

  


  @JsonProperty(JSON_PROPERTY_VAT_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatIncluded(@javax.annotation.Nullable Boolean vatIncluded) {
    this.vatIncluded = vatIncluded;
  }


  /**
   * Сумма НДС
   * @return vatSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVatSum() {
    return vatSum;
  }

  



  /**
   * Сумма Счета в установленной валюте
   * @return sum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getSum() {
    return sum;
  }

  



  /**
   * Сумма входящих платежей по Счету поставщика
   * @return payedSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYED_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPayedSum() {
    return payedSum;
  }

  



  /**
   * Сумма отгруженного
   * @return shippedSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHIPPED_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getShippedSum() {
    return shippedSum;
  }

  



  public CreateInvoiceInBatch200ResponseInner organization(@javax.annotation.Nullable Organization organization) {
    
    this.organization = organization;
    return this;
  }


  /**
   * Get organization
   * @return organization
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Organization getOrganization() {
    return organization;
  }

  


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(@javax.annotation.Nullable Organization organization) {
    this.organization = organization;
  }


  public CreateInvoiceInBatch200ResponseInner organizationAccount(@javax.annotation.Nullable Account organizationAccount) {
    this.organizationAccount = JsonNullable.<Account>of(organizationAccount);
    
    return this;
  }


  /**
   * Метаданные счета юрлица
   * @return organizationAccount
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Account getOrganizationAccount() {
        return organizationAccount.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<Account> getOrganizationAccount_JsonNullable() {
    return organizationAccount;
  }
  
  @JsonProperty(value = JSON_PROPERTY_ORGANIZATION_ACCOUNT, required = false)
  public void setOrganizationAccount_JsonNullable(JsonNullable<Account> organizationAccount) {
    this.organizationAccount = organizationAccount;
  }

  public void setOrganizationAccount(@javax.annotation.Nullable Account organizationAccount) {
    this.organizationAccount = JsonNullable.<Account>of(organizationAccount);
  }


  public CreateInvoiceInBatch200ResponseInner agent(@javax.annotation.Nullable Agent agent) {
    
    this.agent = agent;
    return this;
  }


  /**
   * Метаданные контрагента
   * @return agent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Agent getAgent() {
    return agent;
  }

  


  @JsonProperty(JSON_PROPERTY_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgent(@javax.annotation.Nullable Agent agent) {
    this.agent = agent;
  }


  public CreateInvoiceInBatch200ResponseInner agentAccount(@javax.annotation.Nullable Account agentAccount) {
    this.agentAccount = JsonNullable.<Account>of(agentAccount);
    
    return this;
  }


  /**
   * Метаданные счета контрагента
   * @return agentAccount
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Account getAgentAccount() {
        return agentAccount.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_AGENT_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<Account> getAgentAccount_JsonNullable() {
    return agentAccount;
  }
  
  @JsonProperty(value = JSON_PROPERTY_AGENT_ACCOUNT, required = false)
  public void setAgentAccount_JsonNullable(JsonNullable<Account> agentAccount) {
    this.agentAccount = agentAccount;
  }

  public void setAgentAccount(@javax.annotation.Nullable Account agentAccount) {
    this.agentAccount = JsonNullable.<Account>of(agentAccount);
  }


  public CreateInvoiceInBatch200ResponseInner store(@javax.annotation.Nullable Store store) {
    this.store = JsonNullable.<Store>of(store);
    
    return this;
  }


  /**
   * Метаданные склада
   * @return store
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Store getStore() {
        return store.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_STORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<Store> getStore_JsonNullable() {
    return store;
  }
  
  @JsonProperty(value = JSON_PROPERTY_STORE, required = false)
  public void setStore_JsonNullable(JsonNullable<Store> store) {
    this.store = store;
  }

  public void setStore(@javax.annotation.Nullable Store store) {
    this.store = JsonNullable.<Store>of(store);
  }


  public CreateInvoiceInBatch200ResponseInner state(@javax.annotation.Nullable State state) {
    this.state = JsonNullable.<State>of(state);
    
    return this;
  }


  /**
   * Метаданные статуса счета
   * @return state
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public State getState() {
        return state.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<State> getState_JsonNullable() {
    return state;
  }
  
  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  public void setState_JsonNullable(JsonNullable<State> state) {
    this.state = state;
  }

  public void setState(@javax.annotation.Nullable State state) {
    this.state = JsonNullable.<State>of(state);
  }


  public CreateInvoiceInBatch200ResponseInner contract(@javax.annotation.Nullable Contract contract) {
    this.contract = JsonNullable.<Contract>of(contract);
    
    return this;
  }


  /**
   * Метаданные договора
   * @return contract
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Contract getContract() {
        return contract.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_CONTRACT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<Contract> getContract_JsonNullable() {
    return contract;
  }
  
  @JsonProperty(value = JSON_PROPERTY_CONTRACT, required = false)
  public void setContract_JsonNullable(JsonNullable<Contract> contract) {
    this.contract = contract;
  }

  public void setContract(@javax.annotation.Nullable Contract contract) {
    this.contract = JsonNullable.<Contract>of(contract);
  }


  public CreateInvoiceInBatch200ResponseInner project(@javax.annotation.Nullable Project project) {
    this.project = JsonNullable.<Project>of(project);
    
    return this;
  }


  /**
   * Метаданные проекта
   * @return project
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Project getProject() {
        return project.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_PROJECT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<Project> getProject_JsonNullable() {
    return project;
  }
  
  @JsonProperty(value = JSON_PROPERTY_PROJECT, required = false)
  public void setProject_JsonNullable(JsonNullable<Project> project) {
    this.project = project;
  }

  public void setProject(@javax.annotation.Nullable Project project) {
    this.project = JsonNullable.<Project>of(project);
  }


  public CreateInvoiceInBatch200ResponseInner owner(@javax.annotation.Nullable Employee owner) {
    this.owner = JsonNullable.<Employee>of(owner);
    
    return this;
  }


  /**
   * Владелец (Сотрудник)
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Employee getOwner() {
        return owner.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<Employee> getOwner_JsonNullable() {
    return owner;
  }
  
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  public void setOwner_JsonNullable(JsonNullable<Employee> owner) {
    this.owner = owner;
  }

  public void setOwner(@javax.annotation.Nullable Employee owner) {
    this.owner = JsonNullable.<Employee>of(owner);
  }


  public CreateInvoiceInBatch200ResponseInner group(@javax.annotation.Nullable Group group) {
    
    this.group = group;
    return this;
  }


  /**
   * Get group
   * @return group
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Group getGroup() {
    return group;
  }

  


  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroup(@javax.annotation.Nullable Group group) {
    this.group = group;
  }


  public CreateInvoiceInBatch200ResponseInner attributes(@javax.annotation.Nullable List<AttributeAbstract> attributes) {
    this.attributes = JsonNullable.<List<AttributeAbstract>>of(attributes);
    
    return this;
  }


  public CreateInvoiceInBatch200ResponseInner addAttributesItem(AttributeAbstract attributesItem) {
    if (this.attributes == null || !this.attributes.isPresent()) {
      this.attributes = JsonNullable.<List<AttributeAbstract>>of(new ArrayList<>());
    }
    try {
      this.attributes.get().add(attributesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Коллекция метаданных доп. полей
   * @return attributes
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<AttributeAbstract> getAttributes() {
        return attributes.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<List<AttributeAbstract>> getAttributes_JsonNullable() {
    return attributes;
  }
  
  @JsonProperty(value = JSON_PROPERTY_ATTRIBUTES, required = false)
  public void setAttributes_JsonNullable(JsonNullable<List<AttributeAbstract>> attributes) {
    this.attributes = attributes;
  }

  public void setAttributes(@javax.annotation.Nullable List<AttributeAbstract> attributes) {
    this.attributes = JsonNullable.<List<AttributeAbstract>>of(attributes);
  }


  public CreateInvoiceInBatch200ResponseInner files(@javax.annotation.Nullable FileList files) {
    this.files = JsonNullable.<FileList>of(files);
    
    return this;
  }


  /**
   * Метаданные массива Файлов
   * @return files
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public FileList getFiles() {
        return files.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_FILES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<FileList> getFiles_JsonNullable() {
    return files;
  }
  
  @JsonProperty(value = JSON_PROPERTY_FILES, required = false)
  public void setFiles_JsonNullable(JsonNullable<FileList> files) {
    this.files = files;
  }

  public void setFiles(@javax.annotation.Nullable FileList files) {
    this.files = JsonNullable.<FileList>of(files);
  }


  public CreateInvoiceInBatch200ResponseInner rate(@javax.annotation.Nullable CurrencyRate rate) {
    
    this.rate = rate;
    return this;
  }


  /**
   * Get rate
   * @return rate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CurrencyRate getRate() {
    return rate;
  }

  


  @JsonProperty(JSON_PROPERTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRate(@javax.annotation.Nullable CurrencyRate rate) {
    this.rate = rate;
  }


  public CreateInvoiceInBatch200ResponseInner positions(@javax.annotation.Nullable InvoiceInPositionList positions) {
    
    this.positions = positions;
    return this;
  }


  /**
   * Get positions
   * @return positions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public InvoiceInPositionList getPositions() {
    return positions;
  }

  


  @JsonProperty(JSON_PROPERTY_POSITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPositions(@javax.annotation.Nullable InvoiceInPositionList positions) {
    this.positions = positions;
  }


  public CreateInvoiceInBatch200ResponseInner purchaseOrder(@javax.annotation.Nullable PurchaseOrder purchaseOrder) {
    this.purchaseOrder = JsonNullable.<PurchaseOrder>of(purchaseOrder);
    
    return this;
  }


  /**
   * Заказ поставщику, с которым связан Счет поставщика
   * @return purchaseOrder
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public PurchaseOrder getPurchaseOrder() {
        return purchaseOrder.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_PURCHASE_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<PurchaseOrder> getPurchaseOrder_JsonNullable() {
    return purchaseOrder;
  }
  
  @JsonProperty(value = JSON_PROPERTY_PURCHASE_ORDER, required = false)
  public void setPurchaseOrder_JsonNullable(JsonNullable<PurchaseOrder> purchaseOrder) {
    this.purchaseOrder = purchaseOrder;
  }

  public void setPurchaseOrder(@javax.annotation.Nullable PurchaseOrder purchaseOrder) {
    this.purchaseOrder = JsonNullable.<PurchaseOrder>of(purchaseOrder);
  }


  public CreateInvoiceInBatch200ResponseInner supplies(@javax.annotation.Nullable List<Supply> supplies) {
    this.supplies = JsonNullable.<List<Supply>>of(supplies);
    
    return this;
  }


  public CreateInvoiceInBatch200ResponseInner addSuppliesItem(Supply suppliesItem) {
    if (this.supplies == null || !this.supplies.isPresent()) {
      this.supplies = JsonNullable.<List<Supply>>of(new ArrayList<>());
    }
    try {
      this.supplies.get().add(suppliesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Массив ссылок на связанные приемки
   * @return supplies
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<Supply> getSupplies() {
        return supplies.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_SUPPLIES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<List<Supply>> getSupplies_JsonNullable() {
    return supplies;
  }
  
  @JsonProperty(value = JSON_PROPERTY_SUPPLIES, required = false)
  public void setSupplies_JsonNullable(JsonNullable<List<Supply>> supplies) {
    this.supplies = supplies;
  }

  public void setSupplies(@javax.annotation.Nullable List<Supply> supplies) {
    this.supplies = JsonNullable.<List<Supply>>of(supplies);
  }


  public CreateInvoiceInBatch200ResponseInner payments(@javax.annotation.Nullable List<SalesReturnPaymentsInner> payments) {
    this.payments = JsonNullable.<List<SalesReturnPaymentsInner>>of(payments);
    
    return this;
  }


  public CreateInvoiceInBatch200ResponseInner addPaymentsItem(SalesReturnPaymentsInner paymentsItem) {
    if (this.payments == null || !this.payments.isPresent()) {
      this.payments = JsonNullable.<List<SalesReturnPaymentsInner>>of(new ArrayList<>());
    }
    try {
      this.payments.get().add(paymentsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Массив ссылок на связанные операции
   * @return payments
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<SalesReturnPaymentsInner> getPayments() {
        return payments.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_PAYMENTS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<List<SalesReturnPaymentsInner>> getPayments_JsonNullable() {
    return payments;
  }
  
  @JsonProperty(value = JSON_PROPERTY_PAYMENTS, required = false)
  public void setPayments_JsonNullable(JsonNullable<List<SalesReturnPaymentsInner>> payments) {
    this.payments = payments;
  }

  public void setPayments(@javax.annotation.Nullable List<SalesReturnPaymentsInner> payments) {
    this.payments = JsonNullable.<List<SalesReturnPaymentsInner>>of(payments);
  }


  public CreateInvoiceInBatch200ResponseInner errors(@javax.annotation.Nonnull List<ErrorErrorsInner> errors) {
    
    this.errors = errors;
    return this;
  }


  public CreateInvoiceInBatch200ResponseInner addErrorsItem(ErrorErrorsInner errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ErrorErrorsInner> getErrors() {
    return errors;
  }

  


  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrors(@javax.annotation.Nonnull List<ErrorErrorsInner> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateInvoiceInBatch200ResponseInner createInvoiceInBatch200ResponseInner = (CreateInvoiceInBatch200ResponseInner) o;
    return Objects.equals(this.meta, createInvoiceInBatch200ResponseInner.meta) &&
        Objects.equals(this.id, createInvoiceInBatch200ResponseInner.id) &&
        Objects.equals(this.accountId, createInvoiceInBatch200ResponseInner.accountId) &&
        Objects.equals(this.name, createInvoiceInBatch200ResponseInner.name) &&
        Objects.equals(this.code, createInvoiceInBatch200ResponseInner.code) &&
        Objects.equals(this.externalCode, createInvoiceInBatch200ResponseInner.externalCode) &&
        Objects.equals(this.syncId, createInvoiceInBatch200ResponseInner.syncId) &&
        equalsNullable(this.description, createInvoiceInBatch200ResponseInner.description) &&
        Objects.equals(this.created, createInvoiceInBatch200ResponseInner.created) &&
        Objects.equals(this.deleted, createInvoiceInBatch200ResponseInner.deleted) &&
        Objects.equals(this.updated, createInvoiceInBatch200ResponseInner.updated) &&
        Objects.equals(this.moment, createInvoiceInBatch200ResponseInner.moment) &&
        Objects.equals(this.paymentPlannedMoment, createInvoiceInBatch200ResponseInner.paymentPlannedMoment) &&
        equalsNullable(this.incomingDate, createInvoiceInBatch200ResponseInner.incomingDate) &&
        equalsNullable(this.incomingNumber, createInvoiceInBatch200ResponseInner.incomingNumber) &&
        Objects.equals(this.applicable, createInvoiceInBatch200ResponseInner.applicable) &&
        Objects.equals(this.printed, createInvoiceInBatch200ResponseInner.printed) &&
        Objects.equals(this.published, createInvoiceInBatch200ResponseInner.published) &&
        Objects.equals(this.shared, createInvoiceInBatch200ResponseInner.shared) &&
        Objects.equals(this.vatEnabled, createInvoiceInBatch200ResponseInner.vatEnabled) &&
        Objects.equals(this.vatIncluded, createInvoiceInBatch200ResponseInner.vatIncluded) &&
        Objects.equals(this.vatSum, createInvoiceInBatch200ResponseInner.vatSum) &&
        Objects.equals(this.sum, createInvoiceInBatch200ResponseInner.sum) &&
        Objects.equals(this.payedSum, createInvoiceInBatch200ResponseInner.payedSum) &&
        Objects.equals(this.shippedSum, createInvoiceInBatch200ResponseInner.shippedSum) &&
        Objects.equals(this.organization, createInvoiceInBatch200ResponseInner.organization) &&
        equalsNullable(this.organizationAccount, createInvoiceInBatch200ResponseInner.organizationAccount) &&
        Objects.equals(this.agent, createInvoiceInBatch200ResponseInner.agent) &&
        equalsNullable(this.agentAccount, createInvoiceInBatch200ResponseInner.agentAccount) &&
        equalsNullable(this.store, createInvoiceInBatch200ResponseInner.store) &&
        equalsNullable(this.state, createInvoiceInBatch200ResponseInner.state) &&
        equalsNullable(this.contract, createInvoiceInBatch200ResponseInner.contract) &&
        equalsNullable(this.project, createInvoiceInBatch200ResponseInner.project) &&
        equalsNullable(this.owner, createInvoiceInBatch200ResponseInner.owner) &&
        Objects.equals(this.group, createInvoiceInBatch200ResponseInner.group) &&
        equalsNullable(this.attributes, createInvoiceInBatch200ResponseInner.attributes) &&
        equalsNullable(this.files, createInvoiceInBatch200ResponseInner.files) &&
        Objects.equals(this.rate, createInvoiceInBatch200ResponseInner.rate) &&
        Objects.equals(this.positions, createInvoiceInBatch200ResponseInner.positions) &&
        equalsNullable(this.purchaseOrder, createInvoiceInBatch200ResponseInner.purchaseOrder) &&
        equalsNullable(this.supplies, createInvoiceInBatch200ResponseInner.supplies) &&
        equalsNullable(this.payments, createInvoiceInBatch200ResponseInner.payments) &&
        Objects.equals(this.errors, createInvoiceInBatch200ResponseInner.errors);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, id, accountId, name, code, externalCode, syncId, hashCodeNullable(description), created, deleted, updated, moment, paymentPlannedMoment, hashCodeNullable(incomingDate), hashCodeNullable(incomingNumber), applicable, printed, published, shared, vatEnabled, vatIncluded, vatSum, sum, payedSum, shippedSum, organization, hashCodeNullable(organizationAccount), agent, hashCodeNullable(agentAccount), hashCodeNullable(store), hashCodeNullable(state), hashCodeNullable(contract), hashCodeNullable(project), hashCodeNullable(owner), group, hashCodeNullable(attributes), hashCodeNullable(files), rate, positions, hashCodeNullable(purchaseOrder), hashCodeNullable(supplies), hashCodeNullable(payments), errors);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateInvoiceInBatch200ResponseInner {\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    syncId: ").append(toIndentedString(syncId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    moment: ").append(toIndentedString(moment)).append("\n");
    sb.append("    paymentPlannedMoment: ").append(toIndentedString(paymentPlannedMoment)).append("\n");
    sb.append("    incomingDate: ").append(toIndentedString(incomingDate)).append("\n");
    sb.append("    incomingNumber: ").append(toIndentedString(incomingNumber)).append("\n");
    sb.append("    applicable: ").append(toIndentedString(applicable)).append("\n");
    sb.append("    printed: ").append(toIndentedString(printed)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    vatEnabled: ").append(toIndentedString(vatEnabled)).append("\n");
    sb.append("    vatIncluded: ").append(toIndentedString(vatIncluded)).append("\n");
    sb.append("    vatSum: ").append(toIndentedString(vatSum)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    payedSum: ").append(toIndentedString(payedSum)).append("\n");
    sb.append("    shippedSum: ").append(toIndentedString(shippedSum)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationAccount: ").append(toIndentedString(organizationAccount)).append("\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    agentAccount: ").append(toIndentedString(agentAccount)).append("\n");
    sb.append("    store: ").append(toIndentedString(store)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    contract: ").append(toIndentedString(contract)).append("\n");
    sb.append("    project: ").append(toIndentedString(project)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("    purchaseOrder: ").append(toIndentedString(purchaseOrder)).append("\n");
    sb.append("    supplies: ").append(toIndentedString(supplies)).append("\n");
    sb.append("    payments: ").append(toIndentedString(payments)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `meta` to the URL query string
    if (getMeta() != null) {
      joiner.add(getMeta().toUrlQueryString(prefix + "meta" + suffix));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `accountId` to the URL query string
    if (getAccountId() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%saccountId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAccountId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `code` to the URL query string
    if (getCode() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%scode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `externalCode` to the URL query string
    if (getExternalCode() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sexternalCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExternalCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `syncId` to the URL query string
    if (getSyncId() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssyncId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSyncId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `created` to the URL query string
    if (getCreated() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%screated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreated()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `deleted` to the URL query string
    if (getDeleted() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdeleted%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeleted()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `updated` to the URL query string
    if (getUpdated() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%supdated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdated()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `moment` to the URL query string
    if (getMoment() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%smoment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMoment()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `paymentPlannedMoment` to the URL query string
    if (getPaymentPlannedMoment() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%spaymentPlannedMoment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPaymentPlannedMoment()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `incomingDate` to the URL query string
    if (getIncomingDate() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sincomingDate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIncomingDate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `incomingNumber` to the URL query string
    if (getIncomingNumber() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sincomingNumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getIncomingNumber()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `applicable` to the URL query string
    if (getApplicable() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sapplicable%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getApplicable()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `printed` to the URL query string
    if (getPrinted() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sprinted%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrinted()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `published` to the URL query string
    if (getPublished() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%spublished%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPublished()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `shared` to the URL query string
    if (getShared() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sshared%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getShared()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `vatEnabled` to the URL query string
    if (getVatEnabled() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%svatEnabled%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVatEnabled()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `vatIncluded` to the URL query string
    if (getVatIncluded() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%svatIncluded%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVatIncluded()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `vatSum` to the URL query string
    if (getVatSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%svatSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVatSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `sum` to the URL query string
    if (getSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `payedSum` to the URL query string
    if (getPayedSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%spayedSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPayedSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `shippedSum` to the URL query string
    if (getShippedSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sshippedSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getShippedSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `organization` to the URL query string
    if (getOrganization() != null) {
      joiner.add(getOrganization().toUrlQueryString(prefix + "organization" + suffix));
    }

    // add `organizationAccount` to the URL query string
    if (getOrganizationAccount() != null) {
      joiner.add(getOrganizationAccount().toUrlQueryString(prefix + "organizationAccount" + suffix));
    }

    // add `agent` to the URL query string
    if (getAgent() != null) {
      joiner.add(getAgent().toUrlQueryString(prefix + "agent" + suffix));
    }

    // add `agentAccount` to the URL query string
    if (getAgentAccount() != null) {
      joiner.add(getAgentAccount().toUrlQueryString(prefix + "agentAccount" + suffix));
    }

    // add `store` to the URL query string
    if (getStore() != null) {
      joiner.add(getStore().toUrlQueryString(prefix + "store" + suffix));
    }

    // add `state` to the URL query string
    if (getState() != null) {
      joiner.add(getState().toUrlQueryString(prefix + "state" + suffix));
    }

    // add `contract` to the URL query string
    if (getContract() != null) {
      joiner.add(getContract().toUrlQueryString(prefix + "contract" + suffix));
    }

    // add `project` to the URL query string
    if (getProject() != null) {
      joiner.add(getProject().toUrlQueryString(prefix + "project" + suffix));
    }

    // add `owner` to the URL query string
    if (getOwner() != null) {
      joiner.add(getOwner().toUrlQueryString(prefix + "owner" + suffix));
    }

    // add `group` to the URL query string
    if (getGroup() != null) {
      joiner.add(getGroup().toUrlQueryString(prefix + "group" + suffix));
    }

    // add `attributes` to the URL query string
    if (getAttributes() != null) {
      for (int i = 0; i < getAttributes().size(); i++) {
        if (getAttributes().get(i) != null) {
          joiner.add(getAttributes().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sattributes%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `files` to the URL query string
    if (getFiles() != null) {
      joiner.add(getFiles().toUrlQueryString(prefix + "files" + suffix));
    }

    // add `rate` to the URL query string
    if (getRate() != null) {
      joiner.add(getRate().toUrlQueryString(prefix + "rate" + suffix));
    }

    // add `positions` to the URL query string
    if (getPositions() != null) {
      joiner.add(getPositions().toUrlQueryString(prefix + "positions" + suffix));
    }

    // add `purchaseOrder` to the URL query string
    if (getPurchaseOrder() != null) {
      joiner.add(getPurchaseOrder().toUrlQueryString(prefix + "purchaseOrder" + suffix));
    }

    // add `supplies` to the URL query string
    if (getSupplies() != null) {
      for (int i = 0; i < getSupplies().size(); i++) {
        if (getSupplies().get(i) != null) {
          joiner.add(getSupplies().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%ssupplies%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `payments` to the URL query string
    if (getPayments() != null) {
      for (int i = 0; i < getPayments().size(); i++) {
        if (getPayments().get(i) != null) {
          joiner.add(getPayments().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%spayments%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `errors` to the URL query string
    if (getErrors() != null) {
      for (int i = 0; i < getErrors().size(); i++) {
        if (getErrors().get(i) != null) {
          joiner.add(getErrors().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%serrors%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}
