/*
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.moysklad.remap_1_2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.jackson.nullable.JsonNullable;
import ru.moysklad.remap_1_2.model.Account;
import ru.moysklad.remap_1_2.model.Agent;
import ru.moysklad.remap_1_2.model.AttributeAbstract;
import ru.moysklad.remap_1_2.model.CurrencyRate;
import ru.moysklad.remap_1_2.model.CustomerOrder;
import ru.moysklad.remap_1_2.model.Employee;
import ru.moysklad.remap_1_2.model.Error;
import ru.moysklad.remap_1_2.model.ErrorErrorsInner;
import ru.moysklad.remap_1_2.model.FileList;
import ru.moysklad.remap_1_2.model.Group;
import ru.moysklad.remap_1_2.model.Meta;
import ru.moysklad.remap_1_2.model.Organization;
import ru.moysklad.remap_1_2.model.RetailDemand;
import ru.moysklad.remap_1_2.model.RetailDemandCheque;
import ru.moysklad.remap_1_2.model.RetailDemandGiftCard;
import ru.moysklad.remap_1_2.model.RetailDemandPositionList;
import ru.moysklad.remap_1_2.model.RetailShift;
import ru.moysklad.remap_1_2.model.RetailStore;
import ru.moysklad.remap_1_2.model.State;
import ru.moysklad.remap_1_2.model.Store;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * CreateRetailDemandBatch200ResponseInner
 */
@JsonPropertyOrder({
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_META,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_ID,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_ACCOUNT_ID,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_NAME,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_CODE,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_EXTERNAL_CODE,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_SYNC_ID,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_DESCRIPTION,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_CREATED,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_DELETED,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_UPDATED,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_MOMENT,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_APPLICABLE,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_PRINTED,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_PUBLISHED,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_SHARED,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_VAT_ENABLED,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_VAT_INCLUDED,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_VAT_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_PAYED_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_CASH_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_NO_CASH_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_QR_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_PREPAYMENT_CASH_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_PREPAYMENT_NO_CASH_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_PREPAYMENT_QR_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_ADVANCE_PAYMENT_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_CHECK_NUMBER,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_CHECK_SUM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_DOCUMENT_NUMBER,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_SESSION_NUMBER,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_TAX_SYSTEM,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_STATE,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_ORGANIZATION,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_ORGANIZATION_ACCOUNT,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_AGENT,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_AGENT_ACCOUNT,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_STORE,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_RETAIL_STORE,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_RETAIL_SHIFT,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_CUSTOMER_ORDER,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_OWNER,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_GROUP,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_ATTRIBUTES,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_FILES,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_RATE,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_POSITIONS,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_GIFT_CARDS,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_CHEQUE,
  CreateRetailDemandBatch200ResponseInner.JSON_PROPERTY_ERRORS
})
@JsonTypeName("createRetailDemandBatch_200_response_inner")
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-10T08:38:11.949143335Z[GMT]", comments = "Generator version: 7.14.0")
public class CreateRetailDemandBatch200ResponseInner {

  public static final String JSON_PROPERTY_META = "meta";
  @javax.annotation.Nullable
  private Meta meta;

  public static final String JSON_PROPERTY_ID = "id";
  @javax.annotation.Nullable
  private UUID id;

  public static final String JSON_PROPERTY_ACCOUNT_ID = "accountId";
  @javax.annotation.Nullable
  private UUID accountId;

  public static final String JSON_PROPERTY_NAME = "name";
  @javax.annotation.Nullable
  private String name;

  public static final String JSON_PROPERTY_CODE = "code";
  @javax.annotation.Nullable
  private String code;

  public static final String JSON_PROPERTY_EXTERNAL_CODE = "externalCode";
  @javax.annotation.Nullable
  private String externalCode;

  public static final String JSON_PROPERTY_SYNC_ID = "syncId";
  @javax.annotation.Nullable
  private UUID syncId;

  public static final String JSON_PROPERTY_DESCRIPTION = "description";
  @javax.annotation.Nullable
  private JsonNullable<String> description = JsonNullable.<String>undefined();

  public static final String JSON_PROPERTY_CREATED = "created";
  @javax.annotation.Nullable
  private String created;

  public static final String JSON_PROPERTY_DELETED = "deleted";
  @javax.annotation.Nullable
  private String deleted;

  public static final String JSON_PROPERTY_UPDATED = "updated";
  @javax.annotation.Nullable
  private String updated;

  public static final String JSON_PROPERTY_MOMENT = "moment";
  @javax.annotation.Nullable
  private String moment;

  public static final String JSON_PROPERTY_APPLICABLE = "applicable";
  @javax.annotation.Nullable
  private Boolean applicable;

  public static final String JSON_PROPERTY_PRINTED = "printed";
  @javax.annotation.Nullable
  private Boolean printed;

  public static final String JSON_PROPERTY_PUBLISHED = "published";
  @javax.annotation.Nullable
  private Boolean published;

  public static final String JSON_PROPERTY_SHARED = "shared";
  @javax.annotation.Nullable
  private Boolean shared;

  public static final String JSON_PROPERTY_VAT_ENABLED = "vatEnabled";
  @javax.annotation.Nullable
  private Boolean vatEnabled;

  public static final String JSON_PROPERTY_VAT_INCLUDED = "vatIncluded";
  @javax.annotation.Nullable
  private Boolean vatIncluded;

  public static final String JSON_PROPERTY_VAT_SUM = "vatSum";
  @javax.annotation.Nullable
  private Double vatSum;

  public static final String JSON_PROPERTY_SUM = "sum";
  @javax.annotation.Nullable
  private Double sum;

  public static final String JSON_PROPERTY_PAYED_SUM = "payedSum";
  @javax.annotation.Nullable
  private Double payedSum;

  public static final String JSON_PROPERTY_CASH_SUM = "cashSum";
  @javax.annotation.Nullable
  private Double cashSum;

  public static final String JSON_PROPERTY_NO_CASH_SUM = "noCashSum";
  @javax.annotation.Nullable
  private Double noCashSum;

  public static final String JSON_PROPERTY_QR_SUM = "qrSum";
  @javax.annotation.Nullable
  private Double qrSum;

  public static final String JSON_PROPERTY_PREPAYMENT_CASH_SUM = "prepaymentCashSum";
  @javax.annotation.Nullable
  private Double prepaymentCashSum;

  public static final String JSON_PROPERTY_PREPAYMENT_NO_CASH_SUM = "prepaymentNoCashSum";
  @javax.annotation.Nullable
  private Double prepaymentNoCashSum;

  public static final String JSON_PROPERTY_PREPAYMENT_QR_SUM = "prepaymentQrSum";
  @javax.annotation.Nullable
  private Double prepaymentQrSum;

  public static final String JSON_PROPERTY_ADVANCE_PAYMENT_SUM = "advancePaymentSum";
  @javax.annotation.Nullable
  private Double advancePaymentSum;

  public static final String JSON_PROPERTY_CHECK_NUMBER = "checkNumber";
  @javax.annotation.Nullable
  private String checkNumber;

  public static final String JSON_PROPERTY_CHECK_SUM = "checkSum";
  @javax.annotation.Nullable
  private Double checkSum;

  public static final String JSON_PROPERTY_DOCUMENT_NUMBER = "documentNumber";
  @javax.annotation.Nullable
  private String documentNumber;

  public static final String JSON_PROPERTY_SESSION_NUMBER = "sessionNumber";
  @javax.annotation.Nullable
  private String sessionNumber;

  public static final String JSON_PROPERTY_TAX_SYSTEM = "taxSystem";
  @javax.annotation.Nullable
  private String taxSystem;

  public static final String JSON_PROPERTY_STATE = "state";
  @javax.annotation.Nullable
  private JsonNullable<State> state = JsonNullable.<State>undefined();

  public static final String JSON_PROPERTY_ORGANIZATION = "organization";
  @javax.annotation.Nullable
  private Organization organization;

  public static final String JSON_PROPERTY_ORGANIZATION_ACCOUNT = "organizationAccount";
  @javax.annotation.Nullable
  private JsonNullable<Account> organizationAccount = JsonNullable.<Account>undefined();

  public static final String JSON_PROPERTY_AGENT = "agent";
  @javax.annotation.Nullable
  private Agent agent;

  public static final String JSON_PROPERTY_AGENT_ACCOUNT = "agentAccount";
  @javax.annotation.Nullable
  private JsonNullable<Account> agentAccount = JsonNullable.<Account>undefined();

  public static final String JSON_PROPERTY_STORE = "store";
  @javax.annotation.Nullable
  private Store store;

  public static final String JSON_PROPERTY_RETAIL_STORE = "retailStore";
  @javax.annotation.Nullable
  private RetailStore retailStore;

  public static final String JSON_PROPERTY_RETAIL_SHIFT = "retailShift";
  @javax.annotation.Nullable
  private RetailShift retailShift;

  public static final String JSON_PROPERTY_CUSTOMER_ORDER = "customerOrder";
  @javax.annotation.Nullable
  private JsonNullable<CustomerOrder> customerOrder = JsonNullable.<CustomerOrder>undefined();

  public static final String JSON_PROPERTY_OWNER = "owner";
  @javax.annotation.Nullable
  private JsonNullable<Employee> owner = JsonNullable.<Employee>undefined();

  public static final String JSON_PROPERTY_GROUP = "group";
  @javax.annotation.Nullable
  private Group group;

  public static final String JSON_PROPERTY_ATTRIBUTES = "attributes";
  @javax.annotation.Nullable
  private JsonNullable<List<AttributeAbstract>> attributes = JsonNullable.<List<AttributeAbstract>>undefined();

  public static final String JSON_PROPERTY_FILES = "files";
  @javax.annotation.Nullable
  private JsonNullable<FileList> files = JsonNullable.<FileList>undefined();

  public static final String JSON_PROPERTY_RATE = "rate";
  @javax.annotation.Nullable
  private CurrencyRate rate;

  public static final String JSON_PROPERTY_POSITIONS = "positions";
  @javax.annotation.Nullable
  private RetailDemandPositionList positions;

  public static final String JSON_PROPERTY_GIFT_CARDS = "giftCards";
  @javax.annotation.Nullable
  private JsonNullable<List<RetailDemandGiftCard>> giftCards = JsonNullable.<List<RetailDemandGiftCard>>undefined();

  public static final String JSON_PROPERTY_CHEQUE = "cheque";
  @javax.annotation.Nullable
  private RetailDemandCheque cheque;

  public static final String JSON_PROPERTY_ERRORS = "errors";
  @javax.annotation.Nonnull
  private List<ErrorErrorsInner> errors = new ArrayList<>();

  public CreateRetailDemandBatch200ResponseInner() {
  }
  /**
   * Constructor with only readonly parameters
   */
  @JsonCreator
  public CreateRetailDemandBatch200ResponseInner(
    @JsonProperty(value = JSON_PROPERTY_ID, required = false) UUID id, 
    @JsonProperty(value = JSON_PROPERTY_ACCOUNT_ID, required = false) UUID accountId, 
    @JsonProperty(value = JSON_PROPERTY_CREATED, required = false) String created, 
    @JsonProperty(value = JSON_PROPERTY_DELETED, required = false) String deleted, 
    @JsonProperty(value = JSON_PROPERTY_UPDATED, required = false) String updated, 
    @JsonProperty(value = JSON_PROPERTY_PRINTED, required = false) Boolean printed, 
    @JsonProperty(value = JSON_PROPERTY_PUBLISHED, required = false) Boolean published, 
    @JsonProperty(value = JSON_PROPERTY_VAT_SUM, required = false) Double vatSum, 
    @JsonProperty(value = JSON_PROPERTY_SUM, required = false) Double sum, 
    @JsonProperty(value = JSON_PROPERTY_PAYED_SUM, required = false) Double payedSum, 
    @JsonProperty(value = JSON_PROPERTY_CHEQUE, required = false) RetailDemandCheque cheque
  ) {
    this();
    this.id = id;
    this.accountId = accountId;
    this.created = created;
    this.deleted = deleted;
    this.updated = updated;
    this.printed = printed;
    this.published = published;
    this.vatSum = vatSum;
    this.sum = sum;
    this.payedSum = payedSum;
    this.cheque = cheque;
  }

  public CreateRetailDemandBatch200ResponseInner meta(@javax.annotation.Nullable Meta meta) {
    
    this.meta = meta;
    return this;
  }


  /**
   * Get meta
   * @return meta
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Meta getMeta() {
    return meta;
  }

  


  @JsonProperty(JSON_PROPERTY_META)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMeta(@javax.annotation.Nullable Meta meta) {
    this.meta = meta;
  }


  /**
   * ID Розничной продажи
   * @return id
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getId() {
    return id;
  }

  



  /**
   * ID учетной записи
   * @return accountId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACCOUNT_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getAccountId() {
    return accountId;
  }

  



  public CreateRetailDemandBatch200ResponseInner name(@javax.annotation.Nullable String name) {
    
    this.name = name;
    return this;
  }


  /**
   * Наименование Розничной продажи
   * @return name
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getName() {
    return name;
  }

  


  @JsonProperty(JSON_PROPERTY_NAME)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setName(@javax.annotation.Nullable String name) {
    this.name = name;
  }


  public CreateRetailDemandBatch200ResponseInner code(@javax.annotation.Nullable String code) {
    
    this.code = code;
    return this;
  }


  /**
   * Код Розничной продажи
   * @return code
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCode() {
    return code;
  }

  


  @JsonProperty(JSON_PROPERTY_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCode(@javax.annotation.Nullable String code) {
    this.code = code;
  }


  public CreateRetailDemandBatch200ResponseInner externalCode(@javax.annotation.Nullable String externalCode) {
    
    this.externalCode = externalCode;
    return this;
  }


  /**
   * Внешний код Розничной продажи
   * @return externalCode
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_EXTERNAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getExternalCode() {
    return externalCode;
  }

  


  @JsonProperty(JSON_PROPERTY_EXTERNAL_CODE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setExternalCode(@javax.annotation.Nullable String externalCode) {
    this.externalCode = externalCode;
  }


  public CreateRetailDemandBatch200ResponseInner syncId(@javax.annotation.Nullable UUID syncId) {
    
    this.syncId = syncId;
    return this;
  }


  /**
   * ID синхронизации
   * @return syncId
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SYNC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public UUID getSyncId() {
    return syncId;
  }

  


  @JsonProperty(JSON_PROPERTY_SYNC_ID)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSyncId(@javax.annotation.Nullable UUID syncId) {
    this.syncId = syncId;
  }


  public CreateRetailDemandBatch200ResponseInner description(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
    
    return this;
  }


  /**
   * Комментарий Розничной продажи
   * @return description
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public String getDescription() {
        return description.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_DESCRIPTION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<String> getDescription_JsonNullable() {
    return description;
  }
  
  @JsonProperty(value = JSON_PROPERTY_DESCRIPTION, required = false)
  public void setDescription_JsonNullable(JsonNullable<String> description) {
    this.description = description;
  }

  public void setDescription(@javax.annotation.Nullable String description) {
    this.description = JsonNullable.<String>of(description);
  }


  /**
   * Дата создания
   * @return created
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CREATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreated() {
    return created;
  }

  



  /**
   * Момент последнего удаления Розничной продажи
   * @return deleted
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DELETED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDeleted() {
    return deleted;
  }

  



  /**
   * Момент последнего обновления Розничной продажи
   * @return updated
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_UPDATED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdated() {
    return updated;
  }

  



  public CreateRetailDemandBatch200ResponseInner moment(@javax.annotation.Nullable String moment) {
    
    this.moment = moment;
    return this;
  }


  /**
   * Дата документа
   * @return moment
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MOMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getMoment() {
    return moment;
  }

  


  @JsonProperty(JSON_PROPERTY_MOMENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMoment(@javax.annotation.Nullable String moment) {
    this.moment = moment;
  }


  public CreateRetailDemandBatch200ResponseInner applicable(@javax.annotation.Nullable Boolean applicable) {
    
    this.applicable = applicable;
    return this;
  }


  /**
   * Отметка о проведении
   * @return applicable
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_APPLICABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getApplicable() {
    return applicable;
  }

  


  @JsonProperty(JSON_PROPERTY_APPLICABLE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setApplicable(@javax.annotation.Nullable Boolean applicable) {
    this.applicable = applicable;
  }


  /**
   * Напечатан ли документ
   * @return printed
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PRINTED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPrinted() {
    return printed;
  }

  



  /**
   * Опубликован ли документ
   * @return published
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PUBLISHED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getPublished() {
    return published;
  }

  



  public CreateRetailDemandBatch200ResponseInner shared(@javax.annotation.Nullable Boolean shared) {
    
    this.shared = shared;
    return this;
  }


  /**
   * Общий доступ
   * @return shared
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SHARED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getShared() {
    return shared;
  }

  


  @JsonProperty(JSON_PROPERTY_SHARED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setShared(@javax.annotation.Nullable Boolean shared) {
    this.shared = shared;
  }


  public CreateRetailDemandBatch200ResponseInner vatEnabled(@javax.annotation.Nullable Boolean vatEnabled) {
    
    this.vatEnabled = vatEnabled;
    return this;
  }


  /**
   * Учитывается ли НДС
   * @return vatEnabled
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVatEnabled() {
    return vatEnabled;
  }

  


  @JsonProperty(JSON_PROPERTY_VAT_ENABLED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatEnabled(@javax.annotation.Nullable Boolean vatEnabled) {
    this.vatEnabled = vatEnabled;
  }


  public CreateRetailDemandBatch200ResponseInner vatIncluded(@javax.annotation.Nullable Boolean vatIncluded) {
    
    this.vatIncluded = vatIncluded;
    return this;
  }


  /**
   * Включен ли НДС в цену
   * @return vatIncluded
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Boolean getVatIncluded() {
    return vatIncluded;
  }

  


  @JsonProperty(JSON_PROPERTY_VAT_INCLUDED)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setVatIncluded(@javax.annotation.Nullable Boolean vatIncluded) {
    this.vatIncluded = vatIncluded;
  }


  /**
   * Сумма НДС
   * @return vatSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_VAT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getVatSum() {
    return vatSum;
  }

  



  /**
   * Сумма Розничной продажи в копейках
   * @return sum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getSum() {
    return sum;
  }

  



  /**
   * Сумма входящих платежей по Розничной продаже
   * @return payedSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PAYED_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPayedSum() {
    return payedSum;
  }

  



  public CreateRetailDemandBatch200ResponseInner cashSum(@javax.annotation.Nullable Double cashSum) {
    
    this.cashSum = cashSum;
    return this;
  }


  /**
   * Оплачено наличными
   * @return cashSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CASH_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCashSum() {
    return cashSum;
  }

  


  @JsonProperty(JSON_PROPERTY_CASH_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCashSum(@javax.annotation.Nullable Double cashSum) {
    this.cashSum = cashSum;
  }


  public CreateRetailDemandBatch200ResponseInner noCashSum(@javax.annotation.Nullable Double noCashSum) {
    
    this.noCashSum = noCashSum;
    return this;
  }


  /**
   * Оплачено картой
   * @return noCashSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_NO_CASH_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getNoCashSum() {
    return noCashSum;
  }

  


  @JsonProperty(JSON_PROPERTY_NO_CASH_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setNoCashSum(@javax.annotation.Nullable Double noCashSum) {
    this.noCashSum = noCashSum;
  }


  public CreateRetailDemandBatch200ResponseInner qrSum(@javax.annotation.Nullable Double qrSum) {
    
    this.qrSum = qrSum;
    return this;
  }


  /**
   * Оплачено по QR-коду
   * @return qrSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_QR_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getQrSum() {
    return qrSum;
  }

  


  @JsonProperty(JSON_PROPERTY_QR_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setQrSum(@javax.annotation.Nullable Double qrSum) {
    this.qrSum = qrSum;
  }


  public CreateRetailDemandBatch200ResponseInner prepaymentCashSum(@javax.annotation.Nullable Double prepaymentCashSum) {
    
    this.prepaymentCashSum = prepaymentCashSum;
    return this;
  }


  /**
   * Предоплата наличными
   * @return prepaymentCashSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREPAYMENT_CASH_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrepaymentCashSum() {
    return prepaymentCashSum;
  }

  


  @JsonProperty(JSON_PROPERTY_PREPAYMENT_CASH_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrepaymentCashSum(@javax.annotation.Nullable Double prepaymentCashSum) {
    this.prepaymentCashSum = prepaymentCashSum;
  }


  public CreateRetailDemandBatch200ResponseInner prepaymentNoCashSum(@javax.annotation.Nullable Double prepaymentNoCashSum) {
    
    this.prepaymentNoCashSum = prepaymentNoCashSum;
    return this;
  }


  /**
   * Предоплата картой
   * @return prepaymentNoCashSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREPAYMENT_NO_CASH_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrepaymentNoCashSum() {
    return prepaymentNoCashSum;
  }

  


  @JsonProperty(JSON_PROPERTY_PREPAYMENT_NO_CASH_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrepaymentNoCashSum(@javax.annotation.Nullable Double prepaymentNoCashSum) {
    this.prepaymentNoCashSum = prepaymentNoCashSum;
  }


  public CreateRetailDemandBatch200ResponseInner prepaymentQrSum(@javax.annotation.Nullable Double prepaymentQrSum) {
    
    this.prepaymentQrSum = prepaymentQrSum;
    return this;
  }


  /**
   * Предоплата по QR-коду
   * @return prepaymentQrSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_PREPAYMENT_QR_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getPrepaymentQrSum() {
    return prepaymentQrSum;
  }

  


  @JsonProperty(JSON_PROPERTY_PREPAYMENT_QR_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPrepaymentQrSum(@javax.annotation.Nullable Double prepaymentQrSum) {
    this.prepaymentQrSum = prepaymentQrSum;
  }


  public CreateRetailDemandBatch200ResponseInner advancePaymentSum(@javax.annotation.Nullable Double advancePaymentSum) {
    
    this.advancePaymentSum = advancePaymentSum;
    return this;
  }


  /**
   * Оплачено из аванса
   * @return advancePaymentSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ADVANCE_PAYMENT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getAdvancePaymentSum() {
    return advancePaymentSum;
  }

  


  @JsonProperty(JSON_PROPERTY_ADVANCE_PAYMENT_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAdvancePaymentSum(@javax.annotation.Nullable Double advancePaymentSum) {
    this.advancePaymentSum = advancePaymentSum;
  }


  public CreateRetailDemandBatch200ResponseInner checkNumber(@javax.annotation.Nullable String checkNumber) {
    
    this.checkNumber = checkNumber;
    return this;
  }


  /**
   * Номер чека
   * @return checkNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCheckNumber() {
    return checkNumber;
  }

  


  @JsonProperty(JSON_PROPERTY_CHECK_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckNumber(@javax.annotation.Nullable String checkNumber) {
    this.checkNumber = checkNumber;
  }


  public CreateRetailDemandBatch200ResponseInner checkSum(@javax.annotation.Nullable Double checkSum) {
    
    this.checkSum = checkSum;
    return this;
  }


  /**
   * Сумма чека
   * @return checkSum
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHECK_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getCheckSum() {
    return checkSum;
  }

  


  @JsonProperty(JSON_PROPERTY_CHECK_SUM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCheckSum(@javax.annotation.Nullable Double checkSum) {
    this.checkSum = checkSum;
  }


  public CreateRetailDemandBatch200ResponseInner documentNumber(@javax.annotation.Nullable String documentNumber) {
    
    this.documentNumber = documentNumber;
    return this;
  }


  /**
   * Номер документа
   * @return documentNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_DOCUMENT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDocumentNumber() {
    return documentNumber;
  }

  


  @JsonProperty(JSON_PROPERTY_DOCUMENT_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocumentNumber(@javax.annotation.Nullable String documentNumber) {
    this.documentNumber = documentNumber;
  }


  public CreateRetailDemandBatch200ResponseInner sessionNumber(@javax.annotation.Nullable String sessionNumber) {
    
    this.sessionNumber = sessionNumber;
    return this;
  }


  /**
   * Номер сессии
   * @return sessionNumber
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_SESSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getSessionNumber() {
    return sessionNumber;
  }

  


  @JsonProperty(JSON_PROPERTY_SESSION_NUMBER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setSessionNumber(@javax.annotation.Nullable String sessionNumber) {
    this.sessionNumber = sessionNumber;
  }


  public CreateRetailDemandBatch200ResponseInner taxSystem(@javax.annotation.Nullable String taxSystem) {
    
    this.taxSystem = taxSystem;
    return this;
  }


  /**
   * Код системы налогообложения. Известные значения описаны в TaxSystem
   * @return taxSystem
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_TAX_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getTaxSystem() {
    return taxSystem;
  }

  


  @JsonProperty(JSON_PROPERTY_TAX_SYSTEM)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setTaxSystem(@javax.annotation.Nullable String taxSystem) {
    this.taxSystem = taxSystem;
  }


  public CreateRetailDemandBatch200ResponseInner state(@javax.annotation.Nullable State state) {
    this.state = JsonNullable.<State>of(state);
    
    return this;
  }


  /**
   * Метаданные статуса Розничной продажи
   * @return state
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public State getState() {
        return state.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_STATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<State> getState_JsonNullable() {
    return state;
  }
  
  @JsonProperty(value = JSON_PROPERTY_STATE, required = false)
  public void setState_JsonNullable(JsonNullable<State> state) {
    this.state = state;
  }

  public void setState(@javax.annotation.Nullable State state) {
    this.state = JsonNullable.<State>of(state);
  }


  public CreateRetailDemandBatch200ResponseInner organization(@javax.annotation.Nullable Organization organization) {
    
    this.organization = organization;
    return this;
  }


  /**
   * Get organization
   * @return organization
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Organization getOrganization() {
    return organization;
  }

  


  @JsonProperty(JSON_PROPERTY_ORGANIZATION)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrganization(@javax.annotation.Nullable Organization organization) {
    this.organization = organization;
  }


  public CreateRetailDemandBatch200ResponseInner organizationAccount(@javax.annotation.Nullable Account organizationAccount) {
    this.organizationAccount = JsonNullable.<Account>of(organizationAccount);
    
    return this;
  }


  /**
   * Метаданные счета юрлица
   * @return organizationAccount
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Account getOrganizationAccount() {
        return organizationAccount.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_ORGANIZATION_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<Account> getOrganizationAccount_JsonNullable() {
    return organizationAccount;
  }
  
  @JsonProperty(value = JSON_PROPERTY_ORGANIZATION_ACCOUNT, required = false)
  public void setOrganizationAccount_JsonNullable(JsonNullable<Account> organizationAccount) {
    this.organizationAccount = organizationAccount;
  }

  public void setOrganizationAccount(@javax.annotation.Nullable Account organizationAccount) {
    this.organizationAccount = JsonNullable.<Account>of(organizationAccount);
  }


  public CreateRetailDemandBatch200ResponseInner agent(@javax.annotation.Nullable Agent agent) {
    
    this.agent = agent;
    return this;
  }


  /**
   * Метаданные контрагента или юрлица
   * @return agent
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Agent getAgent() {
    return agent;
  }

  


  @JsonProperty(JSON_PROPERTY_AGENT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setAgent(@javax.annotation.Nullable Agent agent) {
    this.agent = agent;
  }


  public CreateRetailDemandBatch200ResponseInner agentAccount(@javax.annotation.Nullable Account agentAccount) {
    this.agentAccount = JsonNullable.<Account>of(agentAccount);
    
    return this;
  }


  /**
   * Метаданные счета контрагента
   * @return agentAccount
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Account getAgentAccount() {
        return agentAccount.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_AGENT_ACCOUNT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<Account> getAgentAccount_JsonNullable() {
    return agentAccount;
  }
  
  @JsonProperty(value = JSON_PROPERTY_AGENT_ACCOUNT, required = false)
  public void setAgentAccount_JsonNullable(JsonNullable<Account> agentAccount) {
    this.agentAccount = agentAccount;
  }

  public void setAgentAccount(@javax.annotation.Nullable Account agentAccount) {
    this.agentAccount = JsonNullable.<Account>of(agentAccount);
  }


  public CreateRetailDemandBatch200ResponseInner store(@javax.annotation.Nullable Store store) {
    
    this.store = store;
    return this;
  }


  /**
   * Get store
   * @return store
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_STORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Store getStore() {
    return store;
  }

  


  @JsonProperty(JSON_PROPERTY_STORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setStore(@javax.annotation.Nullable Store store) {
    this.store = store;
  }


  public CreateRetailDemandBatch200ResponseInner retailStore(@javax.annotation.Nullable RetailStore retailStore) {
    
    this.retailStore = retailStore;
    return this;
  }


  /**
   * Get retailStore
   * @return retailStore
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETAIL_STORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RetailStore getRetailStore() {
    return retailStore;
  }

  


  @JsonProperty(JSON_PROPERTY_RETAIL_STORE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetailStore(@javax.annotation.Nullable RetailStore retailStore) {
    this.retailStore = retailStore;
  }


  public CreateRetailDemandBatch200ResponseInner retailShift(@javax.annotation.Nullable RetailShift retailShift) {
    
    this.retailShift = retailShift;
    return this;
  }


  /**
   * Get retailShift
   * @return retailShift
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RETAIL_SHIFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RetailShift getRetailShift() {
    return retailShift;
  }

  


  @JsonProperty(JSON_PROPERTY_RETAIL_SHIFT)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRetailShift(@javax.annotation.Nullable RetailShift retailShift) {
    this.retailShift = retailShift;
  }


  public CreateRetailDemandBatch200ResponseInner customerOrder(@javax.annotation.Nullable CustomerOrder customerOrder) {
    this.customerOrder = JsonNullable.<CustomerOrder>of(customerOrder);
    
    return this;
  }


  /**
   * Метаданные заказа покупателя
   * @return customerOrder
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public CustomerOrder getCustomerOrder() {
        return customerOrder.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_CUSTOMER_ORDER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<CustomerOrder> getCustomerOrder_JsonNullable() {
    return customerOrder;
  }
  
  @JsonProperty(value = JSON_PROPERTY_CUSTOMER_ORDER, required = false)
  public void setCustomerOrder_JsonNullable(JsonNullable<CustomerOrder> customerOrder) {
    this.customerOrder = customerOrder;
  }

  public void setCustomerOrder(@javax.annotation.Nullable CustomerOrder customerOrder) {
    this.customerOrder = JsonNullable.<CustomerOrder>of(customerOrder);
  }


  public CreateRetailDemandBatch200ResponseInner owner(@javax.annotation.Nullable Employee owner) {
    this.owner = JsonNullable.<Employee>of(owner);
    
    return this;
  }


  /**
   * Владелец (Сотрудник)
   * @return owner
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public Employee getOwner() {
        return owner.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_OWNER)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<Employee> getOwner_JsonNullable() {
    return owner;
  }
  
  @JsonProperty(value = JSON_PROPERTY_OWNER, required = false)
  public void setOwner_JsonNullable(JsonNullable<Employee> owner) {
    this.owner = owner;
  }

  public void setOwner(@javax.annotation.Nullable Employee owner) {
    this.owner = JsonNullable.<Employee>of(owner);
  }


  public CreateRetailDemandBatch200ResponseInner group(@javax.annotation.Nullable Group group) {
    
    this.group = group;
    return this;
  }


  /**
   * Get group
   * @return group
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Group getGroup() {
    return group;
  }

  


  @JsonProperty(JSON_PROPERTY_GROUP)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGroup(@javax.annotation.Nullable Group group) {
    this.group = group;
  }


  public CreateRetailDemandBatch200ResponseInner attributes(@javax.annotation.Nullable List<AttributeAbstract> attributes) {
    this.attributes = JsonNullable.<List<AttributeAbstract>>of(attributes);
    
    return this;
  }


  public CreateRetailDemandBatch200ResponseInner addAttributesItem(AttributeAbstract attributesItem) {
    if (this.attributes == null || !this.attributes.isPresent()) {
      this.attributes = JsonNullable.<List<AttributeAbstract>>of(new ArrayList<>());
    }
    try {
      this.attributes.get().add(attributesItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Коллекция метаданных доп. полей
   * @return attributes
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<AttributeAbstract> getAttributes() {
        return attributes.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_ATTRIBUTES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<List<AttributeAbstract>> getAttributes_JsonNullable() {
    return attributes;
  }
  
  @JsonProperty(value = JSON_PROPERTY_ATTRIBUTES, required = false)
  public void setAttributes_JsonNullable(JsonNullable<List<AttributeAbstract>> attributes) {
    this.attributes = attributes;
  }

  public void setAttributes(@javax.annotation.Nullable List<AttributeAbstract> attributes) {
    this.attributes = JsonNullable.<List<AttributeAbstract>>of(attributes);
  }


  public CreateRetailDemandBatch200ResponseInner files(@javax.annotation.Nullable FileList files) {
    this.files = JsonNullable.<FileList>of(files);
    
    return this;
  }


  /**
   * Метаданные массива файлов
   * @return files
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public FileList getFiles() {
        return files.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_FILES)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<FileList> getFiles_JsonNullable() {
    return files;
  }
  
  @JsonProperty(value = JSON_PROPERTY_FILES, required = false)
  public void setFiles_JsonNullable(JsonNullable<FileList> files) {
    this.files = files;
  }

  public void setFiles(@javax.annotation.Nullable FileList files) {
    this.files = JsonNullable.<FileList>of(files);
  }


  public CreateRetailDemandBatch200ResponseInner rate(@javax.annotation.Nullable CurrencyRate rate) {
    
    this.rate = rate;
    return this;
  }


  /**
   * Get rate
   * @return rate
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public CurrencyRate getRate() {
    return rate;
  }

  


  @JsonProperty(JSON_PROPERTY_RATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setRate(@javax.annotation.Nullable CurrencyRate rate) {
    this.rate = rate;
  }


  public CreateRetailDemandBatch200ResponseInner positions(@javax.annotation.Nullable RetailDemandPositionList positions) {
    
    this.positions = positions;
    return this;
  }


  /**
   * Get positions
   * @return positions
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_POSITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RetailDemandPositionList getPositions() {
    return positions;
  }

  


  @JsonProperty(JSON_PROPERTY_POSITIONS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPositions(@javax.annotation.Nullable RetailDemandPositionList positions) {
    this.positions = positions;
  }


  public CreateRetailDemandBatch200ResponseInner giftCards(@javax.annotation.Nullable List<RetailDemandGiftCard> giftCards) {
    this.giftCards = JsonNullable.<List<RetailDemandGiftCard>>of(giftCards);
    
    return this;
  }


  public CreateRetailDemandBatch200ResponseInner addGiftCardsItem(RetailDemandGiftCard giftCardsItem) {
    if (this.giftCards == null || !this.giftCards.isPresent()) {
      this.giftCards = JsonNullable.<List<RetailDemandGiftCard>>of(new ArrayList<>());
    }
    try {
      this.giftCards.get().add(giftCardsItem);
    } catch (java.util.NoSuchElementException e) {
      // this can never happen, as we make sure above that the value is present
    }
    return this;
  }

  /**
   * Коллекция подарочных сертификатов, используемых при оплате продажи
   * @return giftCards
   */
  @javax.annotation.Nullable
  @JsonIgnore

  public List<RetailDemandGiftCard> getGiftCards() {
        return giftCards.orElse(null);
  }

  

  @JsonProperty(JSON_PROPERTY_GIFT_CARDS)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)


  public JsonNullable<List<RetailDemandGiftCard>> getGiftCards_JsonNullable() {
    return giftCards;
  }
  
  @JsonProperty(value = JSON_PROPERTY_GIFT_CARDS, required = false)
  public void setGiftCards_JsonNullable(JsonNullable<List<RetailDemandGiftCard>> giftCards) {
    this.giftCards = giftCards;
  }

  public void setGiftCards(@javax.annotation.Nullable List<RetailDemandGiftCard> giftCards) {
    this.giftCards = JsonNullable.<List<RetailDemandGiftCard>>of(giftCards);
  }


  /**
   * Фискальные данные продажи
   * @return cheque
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_CHEQUE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public RetailDemandCheque getCheque() {
    return cheque;
  }

  



  public CreateRetailDemandBatch200ResponseInner errors(@javax.annotation.Nonnull List<ErrorErrorsInner> errors) {
    
    this.errors = errors;
    return this;
  }


  public CreateRetailDemandBatch200ResponseInner addErrorsItem(ErrorErrorsInner errorsItem) {
    if (this.errors == null) {
      this.errors = new ArrayList<>();
    }
    this.errors.add(errorsItem);
    return this;
  }

  /**
   * Get errors
   * @return errors
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ErrorErrorsInner> getErrors() {
    return errors;
  }

  


  @JsonProperty(JSON_PROPERTY_ERRORS)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setErrors(@javax.annotation.Nonnull List<ErrorErrorsInner> errors) {
    this.errors = errors;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CreateRetailDemandBatch200ResponseInner createRetailDemandBatch200ResponseInner = (CreateRetailDemandBatch200ResponseInner) o;
    return Objects.equals(this.meta, createRetailDemandBatch200ResponseInner.meta) &&
        Objects.equals(this.id, createRetailDemandBatch200ResponseInner.id) &&
        Objects.equals(this.accountId, createRetailDemandBatch200ResponseInner.accountId) &&
        Objects.equals(this.name, createRetailDemandBatch200ResponseInner.name) &&
        Objects.equals(this.code, createRetailDemandBatch200ResponseInner.code) &&
        Objects.equals(this.externalCode, createRetailDemandBatch200ResponseInner.externalCode) &&
        Objects.equals(this.syncId, createRetailDemandBatch200ResponseInner.syncId) &&
        equalsNullable(this.description, createRetailDemandBatch200ResponseInner.description) &&
        Objects.equals(this.created, createRetailDemandBatch200ResponseInner.created) &&
        Objects.equals(this.deleted, createRetailDemandBatch200ResponseInner.deleted) &&
        Objects.equals(this.updated, createRetailDemandBatch200ResponseInner.updated) &&
        Objects.equals(this.moment, createRetailDemandBatch200ResponseInner.moment) &&
        Objects.equals(this.applicable, createRetailDemandBatch200ResponseInner.applicable) &&
        Objects.equals(this.printed, createRetailDemandBatch200ResponseInner.printed) &&
        Objects.equals(this.published, createRetailDemandBatch200ResponseInner.published) &&
        Objects.equals(this.shared, createRetailDemandBatch200ResponseInner.shared) &&
        Objects.equals(this.vatEnabled, createRetailDemandBatch200ResponseInner.vatEnabled) &&
        Objects.equals(this.vatIncluded, createRetailDemandBatch200ResponseInner.vatIncluded) &&
        Objects.equals(this.vatSum, createRetailDemandBatch200ResponseInner.vatSum) &&
        Objects.equals(this.sum, createRetailDemandBatch200ResponseInner.sum) &&
        Objects.equals(this.payedSum, createRetailDemandBatch200ResponseInner.payedSum) &&
        Objects.equals(this.cashSum, createRetailDemandBatch200ResponseInner.cashSum) &&
        Objects.equals(this.noCashSum, createRetailDemandBatch200ResponseInner.noCashSum) &&
        Objects.equals(this.qrSum, createRetailDemandBatch200ResponseInner.qrSum) &&
        Objects.equals(this.prepaymentCashSum, createRetailDemandBatch200ResponseInner.prepaymentCashSum) &&
        Objects.equals(this.prepaymentNoCashSum, createRetailDemandBatch200ResponseInner.prepaymentNoCashSum) &&
        Objects.equals(this.prepaymentQrSum, createRetailDemandBatch200ResponseInner.prepaymentQrSum) &&
        Objects.equals(this.advancePaymentSum, createRetailDemandBatch200ResponseInner.advancePaymentSum) &&
        Objects.equals(this.checkNumber, createRetailDemandBatch200ResponseInner.checkNumber) &&
        Objects.equals(this.checkSum, createRetailDemandBatch200ResponseInner.checkSum) &&
        Objects.equals(this.documentNumber, createRetailDemandBatch200ResponseInner.documentNumber) &&
        Objects.equals(this.sessionNumber, createRetailDemandBatch200ResponseInner.sessionNumber) &&
        Objects.equals(this.taxSystem, createRetailDemandBatch200ResponseInner.taxSystem) &&
        equalsNullable(this.state, createRetailDemandBatch200ResponseInner.state) &&
        Objects.equals(this.organization, createRetailDemandBatch200ResponseInner.organization) &&
        equalsNullable(this.organizationAccount, createRetailDemandBatch200ResponseInner.organizationAccount) &&
        Objects.equals(this.agent, createRetailDemandBatch200ResponseInner.agent) &&
        equalsNullable(this.agentAccount, createRetailDemandBatch200ResponseInner.agentAccount) &&
        Objects.equals(this.store, createRetailDemandBatch200ResponseInner.store) &&
        Objects.equals(this.retailStore, createRetailDemandBatch200ResponseInner.retailStore) &&
        Objects.equals(this.retailShift, createRetailDemandBatch200ResponseInner.retailShift) &&
        equalsNullable(this.customerOrder, createRetailDemandBatch200ResponseInner.customerOrder) &&
        equalsNullable(this.owner, createRetailDemandBatch200ResponseInner.owner) &&
        Objects.equals(this.group, createRetailDemandBatch200ResponseInner.group) &&
        equalsNullable(this.attributes, createRetailDemandBatch200ResponseInner.attributes) &&
        equalsNullable(this.files, createRetailDemandBatch200ResponseInner.files) &&
        Objects.equals(this.rate, createRetailDemandBatch200ResponseInner.rate) &&
        Objects.equals(this.positions, createRetailDemandBatch200ResponseInner.positions) &&
        equalsNullable(this.giftCards, createRetailDemandBatch200ResponseInner.giftCards) &&
        Objects.equals(this.cheque, createRetailDemandBatch200ResponseInner.cheque) &&
        Objects.equals(this.errors, createRetailDemandBatch200ResponseInner.errors);
  }

  private static <T> boolean equalsNullable(JsonNullable<T> a, JsonNullable<T> b) {
    return a == b || (a != null && b != null && a.isPresent() && b.isPresent() && Objects.deepEquals(a.get(), b.get()));
  }

  @Override
  public int hashCode() {
    return Objects.hash(meta, id, accountId, name, code, externalCode, syncId, hashCodeNullable(description), created, deleted, updated, moment, applicable, printed, published, shared, vatEnabled, vatIncluded, vatSum, sum, payedSum, cashSum, noCashSum, qrSum, prepaymentCashSum, prepaymentNoCashSum, prepaymentQrSum, advancePaymentSum, checkNumber, checkSum, documentNumber, sessionNumber, taxSystem, hashCodeNullable(state), organization, hashCodeNullable(organizationAccount), agent, hashCodeNullable(agentAccount), store, retailStore, retailShift, hashCodeNullable(customerOrder), hashCodeNullable(owner), group, hashCodeNullable(attributes), hashCodeNullable(files), rate, positions, hashCodeNullable(giftCards), cheque, errors);
  }

  private static <T> int hashCodeNullable(JsonNullable<T> a) {
    if (a == null) {
      return 1;
    }
    return a.isPresent() ? Arrays.deepHashCode(new Object[]{a.get()}) : 31;
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CreateRetailDemandBatch200ResponseInner {\n");
    sb.append("    meta: ").append(toIndentedString(meta)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    accountId: ").append(toIndentedString(accountId)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    code: ").append(toIndentedString(code)).append("\n");
    sb.append("    externalCode: ").append(toIndentedString(externalCode)).append("\n");
    sb.append("    syncId: ").append(toIndentedString(syncId)).append("\n");
    sb.append("    description: ").append(toIndentedString(description)).append("\n");
    sb.append("    created: ").append(toIndentedString(created)).append("\n");
    sb.append("    deleted: ").append(toIndentedString(deleted)).append("\n");
    sb.append("    updated: ").append(toIndentedString(updated)).append("\n");
    sb.append("    moment: ").append(toIndentedString(moment)).append("\n");
    sb.append("    applicable: ").append(toIndentedString(applicable)).append("\n");
    sb.append("    printed: ").append(toIndentedString(printed)).append("\n");
    sb.append("    published: ").append(toIndentedString(published)).append("\n");
    sb.append("    shared: ").append(toIndentedString(shared)).append("\n");
    sb.append("    vatEnabled: ").append(toIndentedString(vatEnabled)).append("\n");
    sb.append("    vatIncluded: ").append(toIndentedString(vatIncluded)).append("\n");
    sb.append("    vatSum: ").append(toIndentedString(vatSum)).append("\n");
    sb.append("    sum: ").append(toIndentedString(sum)).append("\n");
    sb.append("    payedSum: ").append(toIndentedString(payedSum)).append("\n");
    sb.append("    cashSum: ").append(toIndentedString(cashSum)).append("\n");
    sb.append("    noCashSum: ").append(toIndentedString(noCashSum)).append("\n");
    sb.append("    qrSum: ").append(toIndentedString(qrSum)).append("\n");
    sb.append("    prepaymentCashSum: ").append(toIndentedString(prepaymentCashSum)).append("\n");
    sb.append("    prepaymentNoCashSum: ").append(toIndentedString(prepaymentNoCashSum)).append("\n");
    sb.append("    prepaymentQrSum: ").append(toIndentedString(prepaymentQrSum)).append("\n");
    sb.append("    advancePaymentSum: ").append(toIndentedString(advancePaymentSum)).append("\n");
    sb.append("    checkNumber: ").append(toIndentedString(checkNumber)).append("\n");
    sb.append("    checkSum: ").append(toIndentedString(checkSum)).append("\n");
    sb.append("    documentNumber: ").append(toIndentedString(documentNumber)).append("\n");
    sb.append("    sessionNumber: ").append(toIndentedString(sessionNumber)).append("\n");
    sb.append("    taxSystem: ").append(toIndentedString(taxSystem)).append("\n");
    sb.append("    state: ").append(toIndentedString(state)).append("\n");
    sb.append("    organization: ").append(toIndentedString(organization)).append("\n");
    sb.append("    organizationAccount: ").append(toIndentedString(organizationAccount)).append("\n");
    sb.append("    agent: ").append(toIndentedString(agent)).append("\n");
    sb.append("    agentAccount: ").append(toIndentedString(agentAccount)).append("\n");
    sb.append("    store: ").append(toIndentedString(store)).append("\n");
    sb.append("    retailStore: ").append(toIndentedString(retailStore)).append("\n");
    sb.append("    retailShift: ").append(toIndentedString(retailShift)).append("\n");
    sb.append("    customerOrder: ").append(toIndentedString(customerOrder)).append("\n");
    sb.append("    owner: ").append(toIndentedString(owner)).append("\n");
    sb.append("    group: ").append(toIndentedString(group)).append("\n");
    sb.append("    attributes: ").append(toIndentedString(attributes)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    rate: ").append(toIndentedString(rate)).append("\n");
    sb.append("    positions: ").append(toIndentedString(positions)).append("\n");
    sb.append("    giftCards: ").append(toIndentedString(giftCards)).append("\n");
    sb.append("    cheque: ").append(toIndentedString(cheque)).append("\n");
    sb.append("    errors: ").append(toIndentedString(errors)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `meta` to the URL query string
    if (getMeta() != null) {
      joiner.add(getMeta().toUrlQueryString(prefix + "meta" + suffix));
    }

    // add `id` to the URL query string
    if (getId() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sid%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `accountId` to the URL query string
    if (getAccountId() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%saccountId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAccountId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `name` to the URL query string
    if (getName() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sname%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getName()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `code` to the URL query string
    if (getCode() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%scode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `externalCode` to the URL query string
    if (getExternalCode() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sexternalCode%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getExternalCode()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `syncId` to the URL query string
    if (getSyncId() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssyncId%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSyncId()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `description` to the URL query string
    if (getDescription() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdescription%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDescription()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `created` to the URL query string
    if (getCreated() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%screated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreated()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `deleted` to the URL query string
    if (getDeleted() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdeleted%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDeleted()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `updated` to the URL query string
    if (getUpdated() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%supdated%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdated()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `moment` to the URL query string
    if (getMoment() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%smoment%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMoment()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `applicable` to the URL query string
    if (getApplicable() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sapplicable%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getApplicable()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `printed` to the URL query string
    if (getPrinted() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sprinted%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrinted()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `published` to the URL query string
    if (getPublished() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%spublished%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPublished()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `shared` to the URL query string
    if (getShared() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sshared%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getShared()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `vatEnabled` to the URL query string
    if (getVatEnabled() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%svatEnabled%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVatEnabled()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `vatIncluded` to the URL query string
    if (getVatIncluded() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%svatIncluded%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVatIncluded()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `vatSum` to the URL query string
    if (getVatSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%svatSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getVatSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `sum` to the URL query string
    if (getSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `payedSum` to the URL query string
    if (getPayedSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%spayedSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPayedSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `cashSum` to the URL query string
    if (getCashSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%scashSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCashSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `noCashSum` to the URL query string
    if (getNoCashSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%snoCashSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getNoCashSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `qrSum` to the URL query string
    if (getQrSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sqrSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getQrSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `prepaymentCashSum` to the URL query string
    if (getPrepaymentCashSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sprepaymentCashSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrepaymentCashSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `prepaymentNoCashSum` to the URL query string
    if (getPrepaymentNoCashSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sprepaymentNoCashSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrepaymentNoCashSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `prepaymentQrSum` to the URL query string
    if (getPrepaymentQrSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sprepaymentQrSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getPrepaymentQrSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `advancePaymentSum` to the URL query string
    if (getAdvancePaymentSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sadvancePaymentSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getAdvancePaymentSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `checkNumber` to the URL query string
    if (getCheckNumber() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%scheckNumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCheckNumber()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `checkSum` to the URL query string
    if (getCheckSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%scheckSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCheckSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `documentNumber` to the URL query string
    if (getDocumentNumber() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdocumentNumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDocumentNumber()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `sessionNumber` to the URL query string
    if (getSessionNumber() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%ssessionNumber%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getSessionNumber()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `taxSystem` to the URL query string
    if (getTaxSystem() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%staxSystem%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getTaxSystem()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `state` to the URL query string
    if (getState() != null) {
      joiner.add(getState().toUrlQueryString(prefix + "state" + suffix));
    }

    // add `organization` to the URL query string
    if (getOrganization() != null) {
      joiner.add(getOrganization().toUrlQueryString(prefix + "organization" + suffix));
    }

    // add `organizationAccount` to the URL query string
    if (getOrganizationAccount() != null) {
      joiner.add(getOrganizationAccount().toUrlQueryString(prefix + "organizationAccount" + suffix));
    }

    // add `agent` to the URL query string
    if (getAgent() != null) {
      joiner.add(getAgent().toUrlQueryString(prefix + "agent" + suffix));
    }

    // add `agentAccount` to the URL query string
    if (getAgentAccount() != null) {
      joiner.add(getAgentAccount().toUrlQueryString(prefix + "agentAccount" + suffix));
    }

    // add `store` to the URL query string
    if (getStore() != null) {
      joiner.add(getStore().toUrlQueryString(prefix + "store" + suffix));
    }

    // add `retailStore` to the URL query string
    if (getRetailStore() != null) {
      joiner.add(getRetailStore().toUrlQueryString(prefix + "retailStore" + suffix));
    }

    // add `retailShift` to the URL query string
    if (getRetailShift() != null) {
      joiner.add(getRetailShift().toUrlQueryString(prefix + "retailShift" + suffix));
    }

    // add `customerOrder` to the URL query string
    if (getCustomerOrder() != null) {
      joiner.add(getCustomerOrder().toUrlQueryString(prefix + "customerOrder" + suffix));
    }

    // add `owner` to the URL query string
    if (getOwner() != null) {
      joiner.add(getOwner().toUrlQueryString(prefix + "owner" + suffix));
    }

    // add `group` to the URL query string
    if (getGroup() != null) {
      joiner.add(getGroup().toUrlQueryString(prefix + "group" + suffix));
    }

    // add `attributes` to the URL query string
    if (getAttributes() != null) {
      for (int i = 0; i < getAttributes().size(); i++) {
        if (getAttributes().get(i) != null) {
          joiner.add(getAttributes().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sattributes%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `files` to the URL query string
    if (getFiles() != null) {
      joiner.add(getFiles().toUrlQueryString(prefix + "files" + suffix));
    }

    // add `rate` to the URL query string
    if (getRate() != null) {
      joiner.add(getRate().toUrlQueryString(prefix + "rate" + suffix));
    }

    // add `positions` to the URL query string
    if (getPositions() != null) {
      joiner.add(getPositions().toUrlQueryString(prefix + "positions" + suffix));
    }

    // add `giftCards` to the URL query string
    if (getGiftCards() != null) {
      for (int i = 0; i < getGiftCards().size(); i++) {
        if (getGiftCards().get(i) != null) {
          joiner.add(getGiftCards().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%sgiftCards%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    // add `cheque` to the URL query string
    if (getCheque() != null) {
      joiner.add(getCheque().toUrlQueryString(prefix + "cheque" + suffix));
    }

    // add `errors` to the URL query string
    if (getErrors() != null) {
      for (int i = 0; i < getErrors().size(); i++) {
        if (getErrors().get(i) != null) {
          joiner.add(getErrors().get(i).toUrlQueryString(String.format(java.util.Locale.ROOT, "%serrors%s%s", prefix, suffix,
              "".equals(suffix) ? "" : String.format(java.util.Locale.ROOT, "%s%d%s", containerPrefix, i, containerSuffix))));
        }
      }
    }

    return joiner.toString();
  }

}
