/*
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.moysklad.remap_1_2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import ru.moysklad.remap_1_2.model.NotificationNamedEntity;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Уведомление о снижении остатка товара ниже неснижаемого
 */
@JsonPropertyOrder({
  NotificationGoodCountTooLow.JSON_PROPERTY_ACTUAL_BALANCE,
  NotificationGoodCountTooLow.JSON_PROPERTY_GOOD,
  NotificationGoodCountTooLow.JSON_PROPERTY_MINIMUM_BALANCE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-09-01T11:48:09.280618073Z[GMT]", comments = "Generator version: 7.14.0")
public class NotificationGoodCountTooLow extends NotificationAbstract {

  public static final String JSON_PROPERTY_ACTUAL_BALANCE = "actualBalance";
  @javax.annotation.Nullable
  private Double actualBalance;

  public static final String JSON_PROPERTY_GOOD = "good";
  @javax.annotation.Nullable
  private NotificationNamedEntity good;

  public static final String JSON_PROPERTY_MINIMUM_BALANCE = "minimumBalance";
  @javax.annotation.Nullable
  private Double minimumBalance;

  public NotificationGoodCountTooLow() {
  }

  public NotificationGoodCountTooLow actualBalance(@javax.annotation.Nullable Double actualBalance) {
    
    this.actualBalance = actualBalance;
    return this;
  }


  /**
   * Остаток товара
   * @return actualBalance
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_ACTUAL_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getActualBalance() {
    return actualBalance;
  }

  


  @JsonProperty(JSON_PROPERTY_ACTUAL_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setActualBalance(@javax.annotation.Nullable Double actualBalance) {
    this.actualBalance = actualBalance;
  }


  public NotificationGoodCountTooLow good(@javax.annotation.Nullable NotificationNamedEntity good) {
    
    this.good = good;
    return this;
  }


  /**
   * Get good
   * @return good
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_GOOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public NotificationNamedEntity getGood() {
    return good;
  }

  


  @JsonProperty(JSON_PROPERTY_GOOD)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setGood(@javax.annotation.Nullable NotificationNamedEntity good) {
    this.good = good;
  }


  public NotificationGoodCountTooLow minimumBalance(@javax.annotation.Nullable Double minimumBalance) {
    
    this.minimumBalance = minimumBalance;
    return this;
  }


  /**
   * Неснижаемый остаток товара
   * @return minimumBalance
   */
  @javax.annotation.Nullable
  @JsonProperty(JSON_PROPERTY_MINIMUM_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Double getMinimumBalance() {
    return minimumBalance;
  }

  


  @JsonProperty(JSON_PROPERTY_MINIMUM_BALANCE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinimumBalance(@javax.annotation.Nullable Double minimumBalance) {
    this.minimumBalance = minimumBalance;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NotificationGoodCountTooLow notificationGoodCountTooLow = (NotificationGoodCountTooLow) o;
    return Objects.equals(this.actualBalance, notificationGoodCountTooLow.actualBalance) &&
        Objects.equals(this.good, notificationGoodCountTooLow.good) &&
        Objects.equals(this.minimumBalance, notificationGoodCountTooLow.minimumBalance);
  }

  @Override
  public int hashCode() {
    return Objects.hash(actualBalance, good, minimumBalance);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NotificationGoodCountTooLow {\n");
    sb.append("    actualBalance: ").append(toIndentedString(actualBalance)).append("\n");
    sb.append("    good: ").append(toIndentedString(good)).append("\n");
    sb.append("    minimumBalance: ").append(toIndentedString(minimumBalance)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `actualBalance` to the URL query string
    if (getActualBalance() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sactualBalance%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getActualBalance()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `good` to the URL query string
    if (getGood() != null) {
      joiner.add(getGood().toUrlQueryString(prefix + "good" + suffix));
    }

    // add `minimumBalance` to the URL query string
    if (getMinimumBalance() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sminimumBalance%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getMinimumBalance()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}
