/*
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package ru.moysklad.remap_1_2.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import javax.validation.constraints.*;
import javax.validation.Valid;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * ScriptPermissions
 */
@JsonPropertyOrder({
  ScriptPermissions.JSON_PROPERTY_VIEW,
  ScriptPermissions.JSON_PROPERTY_CREATE,
  ScriptPermissions.JSON_PROPERTY_UPDATE,
  ScriptPermissions.JSON_PROPERTY_DELETE,
  ScriptPermissions.JSON_PROPERTY_DONE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-08-25T11:18:02.225766588Z[GMT]", comments = "Generator version: 7.14.0")
public class ScriptPermissions {

  public static final String JSON_PROPERTY_VIEW = "view";
  @javax.annotation.Nullable
  private String view;

  public static final String JSON_PROPERTY_CREATE = "create";
  @javax.annotation.Nullable
  private String create;

  public static final String JSON_PROPERTY_UPDATE = "update";
  @javax.annotation.Nullable
  private String update;

  public static final String JSON_PROPERTY_DELETE = "delete";
  @javax.annotation.Nullable
  private String delete;

  public static final String JSON_PROPERTY_DONE = "done";
  @javax.annotation.Nullable
  private String done;

  public ScriptPermissions() {
  }

  public ScriptPermissions view(@javax.annotation.Nullable String view) {
    
    this.view = view;
    return this;
  }


  /**
   * Смотреть. Известные значения описаны в ScriptPermissionValue.
   * @return view
   */
  @javax.annotation.Nullable


  @JsonProperty(JSON_PROPERTY_VIEW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getView() {
    return view;
  }

  


  @JsonProperty(JSON_PROPERTY_VIEW)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setView(@javax.annotation.Nullable String view) {
    this.view = view;
  }


  public ScriptPermissions create(@javax.annotation.Nullable String create) {
    
    this.create = create;
    return this;
  }


  /**
   * Создавать. Известные значения описаны в ScriptPermissionValue.
   * @return create
   */
  @javax.annotation.Nullable


  @JsonProperty(JSON_PROPERTY_CREATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getCreate() {
    return create;
  }

  


  @JsonProperty(JSON_PROPERTY_CREATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setCreate(@javax.annotation.Nullable String create) {
    this.create = create;
  }


  public ScriptPermissions update(@javax.annotation.Nullable String update) {
    
    this.update = update;
    return this;
  }


  /**
   * Редактировать. Известные значения описаны в ScriptPermissionValue.
   * @return update
   */
  @javax.annotation.Nullable


  @JsonProperty(JSON_PROPERTY_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getUpdate() {
    return update;
  }

  


  @JsonProperty(JSON_PROPERTY_UPDATE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setUpdate(@javax.annotation.Nullable String update) {
    this.update = update;
  }


  public ScriptPermissions delete(@javax.annotation.Nullable String delete) {
    
    this.delete = delete;
    return this;
  }


  /**
   * Удалять. Известные значения описаны в ScriptPermissionValue.
   * @return delete
   */
  @javax.annotation.Nullable


  @JsonProperty(JSON_PROPERTY_DELETE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDelete() {
    return delete;
  }

  


  @JsonProperty(JSON_PROPERTY_DELETE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDelete(@javax.annotation.Nullable String delete) {
    this.delete = delete;
  }


  public ScriptPermissions done(@javax.annotation.Nullable String done) {
    
    this.done = done;
    return this;
  }


  /**
   * Выполнять. Известные значения описаны в ScriptPermissionValue.
   * @return done
   */
  @javax.annotation.Nullable


  @JsonProperty(JSON_PROPERTY_DONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public String getDone() {
    return done;
  }

  


  @JsonProperty(JSON_PROPERTY_DONE)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDone(@javax.annotation.Nullable String done) {
    this.done = done;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ScriptPermissions scriptPermissions = (ScriptPermissions) o;
    return Objects.equals(this.view, scriptPermissions.view) &&
        Objects.equals(this.create, scriptPermissions.create) &&
        Objects.equals(this.update, scriptPermissions.update) &&
        Objects.equals(this.delete, scriptPermissions.delete) &&
        Objects.equals(this.done, scriptPermissions.done);
  }

  @Override
  public int hashCode() {
    return Objects.hash(view, create, update, delete, done);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ScriptPermissions {\n");
    sb.append("    view: ").append(toIndentedString(view)).append("\n");
    sb.append("    create: ").append(toIndentedString(create)).append("\n");
    sb.append("    update: ").append(toIndentedString(update)).append("\n");
    sb.append("    delete: ").append(toIndentedString(delete)).append("\n");
    sb.append("    done: ").append(toIndentedString(done)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `view` to the URL query string
    if (getView() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sview%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getView()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `create` to the URL query string
    if (getCreate() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%screate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getCreate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `update` to the URL query string
    if (getUpdate() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%supdate%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getUpdate()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `delete` to the URL query string
    if (getDelete() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdelete%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDelete()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    // add `done` to the URL query string
    if (getDone() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%sdone%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getDone()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}

