/*
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package org.openapitools.client.api;

import com.fasterxml.jackson.core.type.TypeReference;

import org.openapitools.client.ApiException;
import org.openapitools.client.ApiClient;
import org.openapitools.client.BaseApi;
import org.openapitools.client.Configuration;
import org.openapitools.client.Pair;

import org.openapitools.client.model.AttributeMetaInfo;
import org.openapitools.client.model.AttributeMetaInfoList;
import org.openapitools.client.model.CashIn;
import org.openapitools.client.model.CashInList;
import org.openapitools.client.model.CreateCashInBatch200ResponseInner;
import org.openapitools.client.model.DeleteContractsBatch200ResponseInner;
import org.openapitools.client.model.DocumentMetadata;
import org.openapitools.client.model.ErrorOrArray;
import org.openapitools.client.model.State;
import java.util.UUID;


import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-28T07:26:57.827194517Z[GMT]", comments = "Generator version: 7.14.0")

public class CashInsApi extends BaseApi {

  public CashInsApi() {
    super(Configuration.getDefaultApiClient());
  }

  public CashInsApi(ApiClient apiClient) {
    super(apiClient);
  }

  /**
   * Создать CashIn
   * 
   * @param cashIn  (required)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return CashIn
   * @throws ApiException if fails to make API call
   */
  public CashIn createCashIn(@javax.annotation.Nonnull CashIn cashIn, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.createCashIn(cashIn, expand, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Создать CashIn
   * 
   * @param cashIn  (required)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return CashIn
   * @throws ApiException if fails to make API call
   */
  public CashIn createCashIn(@javax.annotation.Nonnull CashIn cashIn, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = cashIn;
    
    // verify the required parameter 'cashIn' is set
    if (cashIn == null) {
      throw new ApiException(400, "Missing the required parameter 'cashIn' when calling createCashIn");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPair("expand", expand));
    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<CashIn> localVarReturnType = new TypeReference<CashIn>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Массовое создание и обновление CashIn
   * 
   * @param cashIn  (required)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return List&lt;CreateCashInBatch200ResponseInner&gt;
   * @throws ApiException if fails to make API call
   */
  public List<CreateCashInBatch200ResponseInner> createCashInBatch(@javax.annotation.Nonnull List<CashIn> cashIn, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.createCashInBatch(cashIn, expand, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Массовое создание и обновление CashIn
   * 
   * @param cashIn  (required)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return List&lt;CreateCashInBatch200ResponseInner&gt;
   * @throws ApiException if fails to make API call
   */
  public List<CreateCashInBatch200ResponseInner> createCashInBatch(@javax.annotation.Nonnull List<CashIn> cashIn, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = cashIn;
    
    // verify the required parameter 'cashIn' is set
    if (cashIn == null) {
      throw new ApiException(400, "Missing the required parameter 'cashIn' when calling createCashInBatch");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/batch";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPair("expand", expand));
    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<List<CreateCashInBatch200ResponseInner>> localVarReturnType = new TypeReference<List<CreateCashInBatch200ResponseInner>>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Создать доп. поле CashIn
   * 
   * @param attributeMetaInfo  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return AttributeMetaInfo
   * @throws ApiException if fails to make API call
   */
  public AttributeMetaInfo createCashInMetadataAttribute(@javax.annotation.Nonnull AttributeMetaInfo attributeMetaInfo, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.createCashInMetadataAttribute(attributeMetaInfo, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Создать доп. поле CashIn
   * 
   * @param attributeMetaInfo  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return AttributeMetaInfo
   * @throws ApiException if fails to make API call
   */
  public AttributeMetaInfo createCashInMetadataAttribute(@javax.annotation.Nonnull AttributeMetaInfo attributeMetaInfo, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = attributeMetaInfo;
    
    // verify the required parameter 'attributeMetaInfo' is set
    if (attributeMetaInfo == null) {
      throw new ApiException(400, "Missing the required parameter 'attributeMetaInfo' when calling createCashInMetadataAttribute");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/metadata/attributes";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<AttributeMetaInfo> localVarReturnType = new TypeReference<AttributeMetaInfo>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Удалить CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @throws ApiException if fails to make API call
   */
  public void deleteCashIn(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    this.deleteCashIn(id, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Удалить CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @throws ApiException if fails to make API call
   */
  public void deleteCashIn(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteCashIn");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    apiClient.invokeAPI(
        localVarPath,
        "DELETE",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        null
    );
  }

  /**
   * Массовое удаление CashIn
   * 
   * @param cashIn  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return List&lt;DeleteContractsBatch200ResponseInner&gt;
   * @throws ApiException if fails to make API call
   */
  public List<DeleteContractsBatch200ResponseInner> deleteCashInBatch(@javax.annotation.Nonnull List<CashIn> cashIn, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.deleteCashInBatch(cashIn, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Массовое удаление CashIn
   * 
   * @param cashIn  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return List&lt;DeleteContractsBatch200ResponseInner&gt;
   * @throws ApiException if fails to make API call
   */
  public List<DeleteContractsBatch200ResponseInner> deleteCashInBatch(@javax.annotation.Nonnull List<CashIn> cashIn, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = cashIn;
    
    // verify the required parameter 'cashIn' is set
    if (cashIn == null) {
      throw new ApiException(400, "Missing the required parameter 'cashIn' when calling deleteCashInBatch");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/delete";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<List<DeleteContractsBatch200ResponseInner>> localVarReturnType = new TypeReference<List<DeleteContractsBatch200ResponseInner>>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Удалить отдельное доп. поле CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @throws ApiException if fails to make API call
   */
  public void deleteCashInMetadataAttributeById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    this.deleteCashInMetadataAttributeById(id, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Удалить отдельное доп. поле CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @throws ApiException if fails to make API call
   */
  public void deleteCashInMetadataAttributeById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteCashInMetadataAttributeById");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/metadata/attributes/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    apiClient.invokeAPI(
        localVarPath,
        "DELETE",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        null
    );
  }

  /**
   * Удалить отдельный статус CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @throws ApiException if fails to make API call
   */
  public void deleteCashInMetadataStateById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    this.deleteCashInMetadataStateById(id, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Удалить отдельный статус CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @throws ApiException if fails to make API call
   */
  public void deleteCashInMetadataStateById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteCashInMetadataStateById");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/metadata/states/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    apiClient.invokeAPI(
        localVarPath,
        "DELETE",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        null
    );
  }

  /**
   * Получить CashIn
   * 
   * @param id ID сущности (required)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return CashIn
   * @throws ApiException if fails to make API call
   */
  public CashIn getCashInById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.getCashInById(id, expand, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Получить CashIn
   * 
   * @param id ID сущности (required)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return CashIn
   * @throws ApiException if fails to make API call
   */
  public CashIn getCashInById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getCashInById");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPair("expand", expand));
    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<CashIn> localVarReturnType = new TypeReference<CashIn>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Получить список CashIn
   * 
   * @param limit Максимальное количество элементов в выданном списке (максимум 1000) (optional, default to 1000)
   * @param offset Отступ в выданном списке (optional, default to 0)
   * @param search Контекстный поиск по строковым полям сущностей (optional)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return CashInList
   * @throws ApiException if fails to make API call
   */
  public CashInList getCashInList(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String search, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.getCashInList(limit, offset, search, expand, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Получить список CashIn
   * 
   * @param limit Максимальное количество элементов в выданном списке (максимум 1000) (optional, default to 1000)
   * @param offset Отступ в выданном списке (optional, default to 0)
   * @param search Контекстный поиск по строковым полям сущностей (optional)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return CashInList
   * @throws ApiException if fails to make API call
   */
  public CashInList getCashInList(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String search, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // create path and map variables
    String localVarPath = "/entity/cashin";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPair("limit", limit));
    localVarQueryParams.addAll(apiClient.parameterToPair("offset", offset));
    localVarQueryParams.addAll(apiClient.parameterToPair("search", search));
    localVarQueryParams.addAll(apiClient.parameterToPair("expand", expand));
    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<CashInList> localVarReturnType = new TypeReference<CashInList>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Метаданные CashIn
   * 
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return DocumentMetadata
   * @throws ApiException if fails to make API call
   */
  public DocumentMetadata getCashInMetadata(@javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.getCashInMetadata(accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Метаданные CashIn
   * 
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return DocumentMetadata
   * @throws ApiException if fails to make API call
   */
  public DocumentMetadata getCashInMetadata(@javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // create path and map variables
    String localVarPath = "/entity/cashin/metadata";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<DocumentMetadata> localVarReturnType = new TypeReference<DocumentMetadata>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Доп. поля CashIn
   * 
   * @param offset Отступ в выданном списке (optional, default to 0)
   * @param limit Максимальное количество элементов в выданном списке (максимум 1000) (optional, default to 1000)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return AttributeMetaInfoList
   * @throws ApiException if fails to make API call
   */
  public AttributeMetaInfoList getCashInMetadataAttribute(@javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.getCashInMetadataAttribute(offset, limit, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Доп. поля CashIn
   * 
   * @param offset Отступ в выданном списке (optional, default to 0)
   * @param limit Максимальное количество элементов в выданном списке (максимум 1000) (optional, default to 1000)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return AttributeMetaInfoList
   * @throws ApiException if fails to make API call
   */
  public AttributeMetaInfoList getCashInMetadataAttribute(@javax.annotation.Nullable Integer offset, @javax.annotation.Nullable Integer limit, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // create path and map variables
    String localVarPath = "/entity/cashin/metadata/attributes";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPair("offset", offset));
    localVarQueryParams.addAll(apiClient.parameterToPair("limit", limit));
    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<AttributeMetaInfoList> localVarReturnType = new TypeReference<AttributeMetaInfoList>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Отдельное доп. поле CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return AttributeMetaInfo
   * @throws ApiException if fails to make API call
   */
  public AttributeMetaInfo getCashInMetadataAttributeById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.getCashInMetadataAttributeById(id, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Отдельное доп. поле CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return AttributeMetaInfo
   * @throws ApiException if fails to make API call
   */
  public AttributeMetaInfo getCashInMetadataAttributeById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getCashInMetadataAttributeById");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/metadata/attributes/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<AttributeMetaInfo> localVarReturnType = new TypeReference<AttributeMetaInfo>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Отдельный статус CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return State
   * @throws ApiException if fails to make API call
   */
  public State getCashInMetadataStateById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.getCashInMetadataStateById(id, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Отдельный статус CashIn
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return State
   * @throws ApiException if fails to make API call
   */
  public State getCashInMetadataStateById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getCashInMetadataStateById");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/metadata/states/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<State> localVarReturnType = new TypeReference<State>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Шаблон CashIns
   * 
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param body  (optional)
   * @return CashIn
   * @throws ApiException if fails to make API call
   */
  public CashIn getCashInTemplate(@javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body) throws ApiException {
    return this.getCashInTemplate(accept, acceptEncoding, contentType, body, Collections.emptyMap());
  }


  /**
   * Шаблон CashIns
   * 
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param body  (optional)
   * @param additionalHeaders additionalHeaders for this call
   * @return CashIn
   * @throws ApiException if fails to make API call
   */
  public CashIn getCashInTemplate(@javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, @javax.annotation.Nullable Object body, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = body;
    
    // create path and map variables
    String localVarPath = "/entity/cashin/new";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<CashIn> localVarReturnType = new TypeReference<CashIn>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "PUT",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Изменить CashIn
   * 
   * @param id ID сущности (required)
   * @param cashIn  (required)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return CashIn
   * @throws ApiException if fails to make API call
   */
  public CashIn updateCashIn(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull CashIn cashIn, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.updateCashIn(id, cashIn, expand, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Изменить CashIn
   * 
   * @param id ID сущности (required)
   * @param cashIn  (required)
   * @param expand Замена ссылок объектами с помощью expand (optional)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return CashIn
   * @throws ApiException if fails to make API call
   */
  public CashIn updateCashIn(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull CashIn cashIn, @javax.annotation.Nullable String expand, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = cashIn;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling updateCashIn");
    }
    
    // verify the required parameter 'cashIn' is set
    if (cashIn == null) {
      throw new ApiException(400, "Missing the required parameter 'cashIn' when calling updateCashIn");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPair("expand", expand));
    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<CashIn> localVarReturnType = new TypeReference<CashIn>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "PUT",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Обновить отдельное доп. поле CashIn
   * 
   * @param id ID сущности (required)
   * @param attributeMetaInfo  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return AttributeMetaInfo
   * @throws ApiException if fails to make API call
   */
  public AttributeMetaInfo updateCashInMetadataAttributeById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull AttributeMetaInfo attributeMetaInfo, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.updateCashInMetadataAttributeById(id, attributeMetaInfo, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Обновить отдельное доп. поле CashIn
   * 
   * @param id ID сущности (required)
   * @param attributeMetaInfo  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return AttributeMetaInfo
   * @throws ApiException if fails to make API call
   */
  public AttributeMetaInfo updateCashInMetadataAttributeById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull AttributeMetaInfo attributeMetaInfo, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = attributeMetaInfo;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling updateCashInMetadataAttributeById");
    }
    
    // verify the required parameter 'attributeMetaInfo' is set
    if (attributeMetaInfo == null) {
      throw new ApiException(400, "Missing the required parameter 'attributeMetaInfo' when calling updateCashInMetadataAttributeById");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/metadata/attributes/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<AttributeMetaInfo> localVarReturnType = new TypeReference<AttributeMetaInfo>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "PUT",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Обновить отдельный статус CashIn
   * 
   * @param id ID сущности (required)
   * @param state  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return State
   * @throws ApiException if fails to make API call
   */
  public State updateCashInMetadataStateById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull State state, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.updateCashInMetadataStateById(id, state, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Обновить отдельный статус CashIn
   * 
   * @param id ID сущности (required)
   * @param state  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return State
   * @throws ApiException if fails to make API call
   */
  public State updateCashInMetadataStateById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull State state, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = state;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling updateCashInMetadataStateById");
    }
    
    // verify the required parameter 'state' is set
    if (state == null) {
      throw new ApiException(400, "Missing the required parameter 'state' when calling updateCashInMetadataStateById");
    }
    
    // create path and map variables
    String localVarPath = "/entity/cashin/metadata/states/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<State> localVarReturnType = new TypeReference<State>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "PUT",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  @Override
  public <T> T invokeAPI(String url, String method, Object request, TypeReference<T> returnType, Map<String, String> additionalHeaders) throws ApiException {
    String localVarPath = url.replace(apiClient.getBaseURL(), "");
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarHeaderParams.putAll(additionalHeaders);

    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    return apiClient.invokeAPI(
      localVarPath,
        method,
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        request,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        returnType
    );
  }
}
