/*
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Account;
import org.openapitools.client.model.AttributeAbstract;
import org.openapitools.client.model.CommissionReportInCommissionOverhead;
import org.openapitools.client.model.CommissionReportInPositionList;
import org.openapitools.client.model.CommissionReportInReturnedPositionList;
import org.openapitools.client.model.Contract;
import org.openapitools.client.model.Counterparty;
import org.openapitools.client.model.CurrencyRate;
import org.openapitools.client.model.CustomerOrderPaymentsInner;
import org.openapitools.client.model.Employee;
import org.openapitools.client.model.FileList;
import org.openapitools.client.model.Group;
import org.openapitools.client.model.Meta;
import org.openapitools.client.model.Organization;
import org.openapitools.client.model.Project;
import org.openapitools.client.model.SalesChannel;
import org.openapitools.client.model.State;
import org.openapitools.jackson.nullable.JsonNullable;
import com.fasterxml.jackson.annotation.JsonIgnore;
import org.openapitools.jackson.nullable.JsonNullable;
import java.util.NoSuchElementException;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CommissionReportIn
 */
class CommissionReportInTest {
    private final CommissionReportIn model = new CommissionReportIn();

    /**
     * Model tests for CommissionReportIn
     */
    @Test
    void testCommissionReportIn() {
        // TODO: test CommissionReportIn
    }

    /**
     * Test the property 'meta'
     */
    @Test
    void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'agent'
     */
    @Test
    void agentTest() {
        // TODO: test agent
    }

    /**
     * Test the property 'agentAccount'
     */
    @Test
    void agentAccountTest() {
        // TODO: test agentAccount
    }

    /**
     * Test the property 'applicable'
     */
    @Test
    void applicableTest() {
        // TODO: test applicable
    }

    /**
     * Test the property 'attributes'
     */
    @Test
    void attributesTest() {
        // TODO: test attributes
    }

    /**
     * Test the property 'code'
     */
    @Test
    void codeTest() {
        // TODO: test code
    }

    /**
     * Test the property 'commissionOverhead'
     */
    @Test
    void commissionOverheadTest() {
        // TODO: test commissionOverhead
    }

    /**
     * Test the property 'commissionPeriodEnd'
     */
    @Test
    void commissionPeriodEndTest() {
        // TODO: test commissionPeriodEnd
    }

    /**
     * Test the property 'commissionPeriodStart'
     */
    @Test
    void commissionPeriodStartTest() {
        // TODO: test commissionPeriodStart
    }

    /**
     * Test the property 'commitentSum'
     */
    @Test
    void commitentSumTest() {
        // TODO: test commitentSum
    }

    /**
     * Test the property 'contract'
     */
    @Test
    void contractTest() {
        // TODO: test contract
    }

    /**
     * Test the property 'created'
     */
    @Test
    void createdTest() {
        // TODO: test created
    }

    /**
     * Test the property 'deleted'
     */
    @Test
    void deletedTest() {
        // TODO: test deleted
    }

    /**
     * Test the property 'description'
     */
    @Test
    void descriptionTest() {
        // TODO: test description
    }

    /**
     * Test the property 'externalCode'
     */
    @Test
    void externalCodeTest() {
        // TODO: test externalCode
    }

    /**
     * Test the property 'files'
     */
    @Test
    void filesTest() {
        // TODO: test files
    }

    /**
     * Test the property 'group'
     */
    @Test
    void groupTest() {
        // TODO: test group
    }

    /**
     * Test the property 'moment'
     */
    @Test
    void momentTest() {
        // TODO: test moment
    }

    /**
     * Test the property 'name'
     */
    @Test
    void nameTest() {
        // TODO: test name
    }

    /**
     * Test the property 'organization'
     */
    @Test
    void organizationTest() {
        // TODO: test organization
    }

    /**
     * Test the property 'organizationAccount'
     */
    @Test
    void organizationAccountTest() {
        // TODO: test organizationAccount
    }

    /**
     * Test the property 'owner'
     */
    @Test
    void ownerTest() {
        // TODO: test owner
    }

    /**
     * Test the property 'payedSum'
     */
    @Test
    void payedSumTest() {
        // TODO: test payedSum
    }

    /**
     * Test the property 'positions'
     */
    @Test
    void positionsTest() {
        // TODO: test positions
    }

    /**
     * Test the property 'printed'
     */
    @Test
    void printedTest() {
        // TODO: test printed
    }

    /**
     * Test the property 'project'
     */
    @Test
    void projectTest() {
        // TODO: test project
    }

    /**
     * Test the property 'published'
     */
    @Test
    void publishedTest() {
        // TODO: test published
    }

    /**
     * Test the property 'rate'
     */
    @Test
    void rateTest() {
        // TODO: test rate
    }

    /**
     * Test the property 'returnToCommissionerPositions'
     */
    @Test
    void returnToCommissionerPositionsTest() {
        // TODO: test returnToCommissionerPositions
    }

    /**
     * Test the property 'rewardPercent'
     */
    @Test
    void rewardPercentTest() {
        // TODO: test rewardPercent
    }

    /**
     * Test the property 'rewardType'
     */
    @Test
    void rewardTypeTest() {
        // TODO: test rewardType
    }

    /**
     * Test the property 'salesChannel'
     */
    @Test
    void salesChannelTest() {
        // TODO: test salesChannel
    }

    /**
     * Test the property 'shared'
     */
    @Test
    void sharedTest() {
        // TODO: test shared
    }

    /**
     * Test the property 'state'
     */
    @Test
    void stateTest() {
        // TODO: test state
    }

    /**
     * Test the property 'sum'
     */
    @Test
    void sumTest() {
        // TODO: test sum
    }

    /**
     * Test the property 'syncId'
     */
    @Test
    void syncIdTest() {
        // TODO: test syncId
    }

    /**
     * Test the property 'updated'
     */
    @Test
    void updatedTest() {
        // TODO: test updated
    }

    /**
     * Test the property 'vatEnabled'
     */
    @Test
    void vatEnabledTest() {
        // TODO: test vatEnabled
    }

    /**
     * Test the property 'vatIncluded'
     */
    @Test
    void vatIncludedTest() {
        // TODO: test vatIncluded
    }

    /**
     * Test the property 'vatSum'
     */
    @Test
    void vatSumTest() {
        // TODO: test vatSum
    }

    /**
     * Test the property 'payments'
     */
    @Test
    void paymentsTest() {
        // TODO: test payments
    }

}
