/*
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import org.openapitools.client.model.Assortment;
import org.openapitools.client.model.CommissionReportInReturnedPosition;
import org.openapitools.client.model.Error;
import org.openapitools.client.model.ErrorErrorsInner;
import org.openapitools.client.model.Meta;
import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Disabled;
import org.junit.jupiter.api.Test;

/**
 * Model tests for CreateCommissionReportInReturnedPositions200ResponseInner
 */
class CreateCommissionReportInReturnedPositions200ResponseInnerTest {
    private final CreateCommissionReportInReturnedPositions200ResponseInner model = new CreateCommissionReportInReturnedPositions200ResponseInner();

    /**
     * Model tests for CreateCommissionReportInReturnedPositions200ResponseInner
     */
    @Test
    void testCreateCommissionReportInReturnedPositions200ResponseInner() {
        // TODO: test CreateCommissionReportInReturnedPositions200ResponseInner
    }

    /**
     * Test the property 'meta'
     */
    @Test
    void metaTest() {
        // TODO: test meta
    }

    /**
     * Test the property 'id'
     */
    @Test
    void idTest() {
        // TODO: test id
    }

    /**
     * Test the property 'accountId'
     */
    @Test
    void accountIdTest() {
        // TODO: test accountId
    }

    /**
     * Test the property 'quantity'
     */
    @Test
    void quantityTest() {
        // TODO: test quantity
    }

    /**
     * Test the property 'price'
     */
    @Test
    void priceTest() {
        // TODO: test price
    }

    /**
     * Test the property 'reward'
     */
    @Test
    void rewardTest() {
        // TODO: test reward
    }

    /**
     * Test the property 'vat'
     */
    @Test
    void vatTest() {
        // TODO: test vat
    }

    /**
     * Test the property 'vatEnabled'
     */
    @Test
    void vatEnabledTest() {
        // TODO: test vatEnabled
    }

    /**
     * Test the property 'assortment'
     */
    @Test
    void assortmentTest() {
        // TODO: test assortment
    }

    /**
     * Test the property 'errors'
     */
    @Test
    void errorsTest() {
        // TODO: test errors
    }

}
