/*
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

package ru.moysklad.remap_1_2.api;

import com.fasterxml.jackson.core.type.TypeReference;

import ru.moysklad.remap_1_2.ApiException;
import ru.moysklad.remap_1_2.ApiClient;
import ru.moysklad.remap_1_2.BaseApi;
import ru.moysklad.remap_1_2.Configuration;
import ru.moysklad.remap_1_2.Pair;

import ru.moysklad.remap_1_2.model.CreateProcessingPlanFoldersBatch200ResponseInner;
import ru.moysklad.remap_1_2.model.DeleteContractsBatch200ResponseInner;
import ru.moysklad.remap_1_2.model.ErrorOrArray;
import ru.moysklad.remap_1_2.model.Metadata;
import ru.moysklad.remap_1_2.model.ProcessingPlanFolder;
import ru.moysklad.remap_1_2.model.ProcessingPlanFolderList;
import java.util.UUID;


import java.util.ArrayList;
import java.util.Collections;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.StringJoiner;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-06-18T09:20:10.487321760Z[GMT]", comments = "Generator version: 7.14.0")

public class ProcessingPlanFoldersApi extends BaseApi {

  public ProcessingPlanFoldersApi() {
    super(Configuration.getDefaultApiClient());
  }

  public ProcessingPlanFoldersApi(ApiClient apiClient) {
    super(apiClient);
  }

  /**
   * Создать группу техкарт
   * 
   * @param processingPlanFolder  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return ProcessingPlanFolder
   * @throws ApiException if fails to make API call
   */
  public ProcessingPlanFolder createProcessingPlanFolder(@javax.annotation.Nonnull ProcessingPlanFolder processingPlanFolder, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.createProcessingPlanFolder(processingPlanFolder, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Создать группу техкарт
   * 
   * @param processingPlanFolder  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return ProcessingPlanFolder
   * @throws ApiException if fails to make API call
   */
  public ProcessingPlanFolder createProcessingPlanFolder(@javax.annotation.Nonnull ProcessingPlanFolder processingPlanFolder, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = processingPlanFolder;
    
    // verify the required parameter 'processingPlanFolder' is set
    if (processingPlanFolder == null) {
      throw new ApiException(400, "Missing the required parameter 'processingPlanFolder' when calling createProcessingPlanFolder");
    }
    
    // create path and map variables
    String localVarPath = "/entity/processingplanfolder";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<ProcessingPlanFolder> localVarReturnType = new TypeReference<ProcessingPlanFolder>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Массовое создание и обновление групп техкарт
   * 
   * @param processingPlanFolder  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return List&lt;CreateProcessingPlanFoldersBatch200ResponseInner&gt;
   * @throws ApiException if fails to make API call
   */
  public List<CreateProcessingPlanFoldersBatch200ResponseInner> createProcessingPlanFoldersBatch(@javax.annotation.Nonnull List<ProcessingPlanFolder> processingPlanFolder, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.createProcessingPlanFoldersBatch(processingPlanFolder, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Массовое создание и обновление групп техкарт
   * 
   * @param processingPlanFolder  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return List&lt;CreateProcessingPlanFoldersBatch200ResponseInner&gt;
   * @throws ApiException if fails to make API call
   */
  public List<CreateProcessingPlanFoldersBatch200ResponseInner> createProcessingPlanFoldersBatch(@javax.annotation.Nonnull List<ProcessingPlanFolder> processingPlanFolder, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = processingPlanFolder;
    
    // verify the required parameter 'processingPlanFolder' is set
    if (processingPlanFolder == null) {
      throw new ApiException(400, "Missing the required parameter 'processingPlanFolder' when calling createProcessingPlanFoldersBatch");
    }
    
    // create path and map variables
    String localVarPath = "/entity/processingplanfolder/batch";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<List<CreateProcessingPlanFoldersBatch200ResponseInner>> localVarReturnType = new TypeReference<List<CreateProcessingPlanFoldersBatch200ResponseInner>>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Удалить группу техкарт
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @throws ApiException if fails to make API call
   */
  public void deleteProcessingPlanFolder(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    this.deleteProcessingPlanFolder(id, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Удалить группу техкарт
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @throws ApiException if fails to make API call
   */
  public void deleteProcessingPlanFolder(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling deleteProcessingPlanFolder");
    }
    
    // create path and map variables
    String localVarPath = "/entity/processingplanfolder/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    apiClient.invokeAPI(
        localVarPath,
        "DELETE",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        null
    );
  }

  /**
   * Массовое удаление групп техкарт
   * 
   * @param processingPlanFolder  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return List&lt;DeleteContractsBatch200ResponseInner&gt;
   * @throws ApiException if fails to make API call
   */
  public List<DeleteContractsBatch200ResponseInner> deleteProcessingPlanFoldersBatch(@javax.annotation.Nonnull List<ProcessingPlanFolder> processingPlanFolder, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.deleteProcessingPlanFoldersBatch(processingPlanFolder, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Массовое удаление групп техкарт
   * 
   * @param processingPlanFolder  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return List&lt;DeleteContractsBatch200ResponseInner&gt;
   * @throws ApiException if fails to make API call
   */
  public List<DeleteContractsBatch200ResponseInner> deleteProcessingPlanFoldersBatch(@javax.annotation.Nonnull List<ProcessingPlanFolder> processingPlanFolder, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = processingPlanFolder;
    
    // verify the required parameter 'processingPlanFolder' is set
    if (processingPlanFolder == null) {
      throw new ApiException(400, "Missing the required parameter 'processingPlanFolder' when calling deleteProcessingPlanFoldersBatch");
    }
    
    // create path and map variables
    String localVarPath = "/entity/processingplanfolder/delete";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<List<DeleteContractsBatch200ResponseInner>> localVarReturnType = new TypeReference<List<DeleteContractsBatch200ResponseInner>>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "POST",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Получить группу техкарт
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @return ProcessingPlanFolder
   * @throws ApiException if fails to make API call
   */
  public ProcessingPlanFolder getProcessingPlanFolderById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding) throws ApiException {
    return this.getProcessingPlanFolderById(id, accept, acceptEncoding, Collections.emptyMap());
  }


  /**
   * Получить группу техкарт
   * 
   * @param id ID сущности (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param additionalHeaders additionalHeaders for this call
   * @return ProcessingPlanFolder
   * @throws ApiException if fails to make API call
   */
  public ProcessingPlanFolder getProcessingPlanFolderById(@javax.annotation.Nonnull UUID id, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling getProcessingPlanFolderById");
    }
    
    // create path and map variables
    String localVarPath = "/entity/processingplanfolder/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<ProcessingPlanFolder> localVarReturnType = new TypeReference<ProcessingPlanFolder>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Метаданные групп техкарт
   * 
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return Metadata
   * @throws ApiException if fails to make API call
   */
  public Metadata getProcessingPlanFolderMetadata(@javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.getProcessingPlanFolderMetadata(accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Метаданные групп техкарт
   * 
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return Metadata
   * @throws ApiException if fails to make API call
   */
  public Metadata getProcessingPlanFolderMetadata(@javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // create path and map variables
    String localVarPath = "/entity/processingplanfolder/metadata";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<Metadata> localVarReturnType = new TypeReference<Metadata>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Получить список групп техкарт
   * 
   * @param limit Максимальное количество элементов в выданном списке (максимум 1000) (optional, default to 1000)
   * @param offset Отступ в выданном списке (optional, default to 0)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return ProcessingPlanFolderList
   * @throws ApiException if fails to make API call
   */
  public ProcessingPlanFolderList getProcessingPlanFolders(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.getProcessingPlanFolders(limit, offset, accept, acceptEncoding, contentType, Collections.emptyMap());
  }

  /**
   * Получить список групп техкарт
   * 
   
   
   
   
   
   * @param options request options such as pagination, filters, expands, fields, sorting and additional headers
   * @return ProcessingPlanFolderList
   * @throws ApiException if fails to make API call
   */
  public ProcessingPlanFolderList getProcessingPlanFolders(RequestOptions options) throws ApiException {
    RequestOptions effectiveOptions = RequestOptions.emptyIfNull(options);
    return this.getProcessingPlanFolders((Integer) effectiveOptions.get("limit"), (Integer) effectiveOptions.get("offset"), null, null, null, effectiveOptions.getAdditionalHeaders());
  }


  /**
   * Получить список групп техкарт
   * 
   * @param limit Максимальное количество элементов в выданном списке (максимум 1000) (optional, default to 1000)
   * @param offset Отступ в выданном списке (optional, default to 0)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return ProcessingPlanFolderList
   * @throws ApiException if fails to make API call
   */
  public ProcessingPlanFolderList getProcessingPlanFolders(@javax.annotation.Nullable Integer limit, @javax.annotation.Nullable Integer offset, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = null;
    
    // create path and map variables
    String localVarPath = "/entity/processingplanfolder";

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarQueryParams.addAll(apiClient.parameterToPair("limit", limit));
    localVarQueryParams.addAll(apiClient.parameterToPair("offset", offset));
    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<ProcessingPlanFolderList> localVarReturnType = new TypeReference<ProcessingPlanFolderList>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "GET",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  /**
   * Изменить группу техкарт
   * 
   * @param id ID сущности (required)
   * @param processingPlanFolder  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @return ProcessingPlanFolder
   * @throws ApiException if fails to make API call
   */
  public ProcessingPlanFolder updateProcessingPlanFolder(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull ProcessingPlanFolder processingPlanFolder, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType) throws ApiException {
    return this.updateProcessingPlanFolder(id, processingPlanFolder, accept, acceptEncoding, contentType, Collections.emptyMap());
  }


  /**
   * Изменить группу техкарт
   * 
   * @param id ID сущности (required)
   * @param processingPlanFolder  (required)
   * @param accept  (optional, default to application/json;charset&#x3D;utf-8)
   * @param acceptEncoding  (optional, default to gzip, deflate, br)
   * @param contentType  (optional, default to application/json)
   * @param additionalHeaders additionalHeaders for this call
   * @return ProcessingPlanFolder
   * @throws ApiException if fails to make API call
   */
  public ProcessingPlanFolder updateProcessingPlanFolder(@javax.annotation.Nonnull UUID id, @javax.annotation.Nonnull ProcessingPlanFolder processingPlanFolder, @javax.annotation.Nullable String accept, @javax.annotation.Nullable String acceptEncoding, @javax.annotation.Nullable String contentType, Map<String, String> additionalHeaders) throws ApiException {
    Object localVarPostBody = processingPlanFolder;
    
    // verify the required parameter 'id' is set
    if (id == null) {
      throw new ApiException(400, "Missing the required parameter 'id' when calling updateProcessingPlanFolder");
    }
    
    // verify the required parameter 'processingPlanFolder' is set
    if (processingPlanFolder == null) {
      throw new ApiException(400, "Missing the required parameter 'processingPlanFolder' when calling updateProcessingPlanFolder");
    }
    
    // create path and map variables
    String localVarPath = "/entity/processingplanfolder/{id}"
      .replaceAll("\\{" + "id" + "\\}", apiClient.escapeString(apiClient.parameterToString(id)));

    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    String localVarQueryParameterBaseName;
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    if (accept != null)
      localVarHeaderParams.put("accept", apiClient.parameterToString(accept));
if (acceptEncoding != null)
      localVarHeaderParams.put("Accept-Encoding", apiClient.parameterToString(acceptEncoding));
if (contentType != null)
      localVarHeaderParams.put("Content-Type", apiClient.parameterToString(contentType));

    localVarHeaderParams.putAll(additionalHeaders);

    
    
    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    TypeReference<ProcessingPlanFolder> localVarReturnType = new TypeReference<ProcessingPlanFolder>() {};
    return apiClient.invokeAPI(
        localVarPath,
        "PUT",
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        localVarPostBody,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        localVarReturnType
    );
  }

  @Override
  public <T> T invokeAPI(String url, String method, Object request, TypeReference<T> returnType, Map<String, String> additionalHeaders) throws ApiException {
    String localVarPath = url.replace(apiClient.getBaseURL(), "");
    StringJoiner localVarQueryStringJoiner = new StringJoiner("&");
    List<Pair> localVarQueryParams = new ArrayList<Pair>();
    List<Pair> localVarCollectionQueryParams = new ArrayList<Pair>();
    Map<String, String> localVarHeaderParams = new HashMap<String, String>();
    Map<String, String> localVarCookieParams = new HashMap<String, String>();
    Map<String, Object> localVarFormParams = new HashMap<String, Object>();

    localVarHeaderParams.putAll(additionalHeaders);

    final String[] localVarAccepts = {
          "application/json;charset=utf-8"
        };
    final String localVarAccept = apiClient.selectHeaderAccept(localVarAccepts);

    final String[] localVarContentTypes = {
      "application/json"
    };
    final String localVarContentType = apiClient.selectHeaderContentType(localVarContentTypes);

    String[] localVarAuthNames = new String[] { "basicAuth", "bearerAuth" };

    return apiClient.invokeAPI(
      localVarPath,
        method,
        localVarQueryParams,
        localVarCollectionQueryParams,
        localVarQueryStringJoiner.toString(),
        request,
        localVarHeaderParams,
        localVarCookieParams,
        localVarFormParams,
        localVarAccept,
        localVarContentType,
        localVarAuthNames,
        returnType
    );
  }
}
