/*
 * МойСклад JSON API
 * API для манипуляции с сущностями и создания отчетов в онлайн-сервисе МойСклад.  ## Аутентификация  МойСклад поддерживает аутентификацию по протоколу Basic Auth и с использованием токена доступа: - Basic Auth: заголовок `Authorization` со значением пары `логин:пароль`, закодированным в Base64 - Bearer Token: заголовок `Authorization` со значением `Bearer <Access-Token>`  ## Ограничения  - Не более 45 запросов за 3 секундный период от аккаунта - Не более 5 параллельных запросов от одного пользователя   - Не более 20 параллельных запросов от аккаунта - Не более 20 Мб данных в одном запросе - Максимум 1000 элементов в массиве - Обязательное использование сжатия gzip 
 *
 * The version of the OpenAPI document: 1.0.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package org.openapitools.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.fasterxml.jackson.annotation.JsonTypeName;
import java.io.UnsupportedEncodingException;
import java.net.URLEncoder;
import java.util.StringJoiner;

/**
 * Поле суммы по связанной операции расходного ордера. Комбинируется через &#x60;allOf&#x60; с телом документа в элементах &#x60;operations[]&#x60;. 
 */
@JsonPropertyOrder({
  CashOutOperationLinkedSum.JSON_PROPERTY_LINKED_SUM
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2026-04-28T11:37:33.115271248Z[GMT]", comments = "Generator version: 7.14.0")
public class CashOutOperationLinkedSum {
  public static final String JSON_PROPERTY_LINKED_SUM = "linkedSum";
  @javax.annotation.Nonnull
  private Double linkedSum;

  public CashOutOperationLinkedSum() {
  }

  public CashOutOperationLinkedSum linkedSum(@javax.annotation.Nonnull Double linkedSum) {
    
    this.linkedSum = linkedSum;
    return this;
  }

  /**
   * Сумма, оплаченная по данному документу
   * @return linkedSum
   */
  @javax.annotation.Nonnull
  @JsonProperty(JSON_PROPERTY_LINKED_SUM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Double getLinkedSum() {
    return linkedSum;
  }

  


  @JsonProperty(JSON_PROPERTY_LINKED_SUM)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLinkedSum(@javax.annotation.Nonnull Double linkedSum) {
    this.linkedSum = linkedSum;
  }

  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    CashOutOperationLinkedSum cashOutOperationLinkedSum = (CashOutOperationLinkedSum) o;
    return Objects.equals(this.linkedSum, cashOutOperationLinkedSum.linkedSum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(linkedSum);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class CashOutOperationLinkedSum {\n");
    sb.append("    linkedSum: ").append(toIndentedString(linkedSum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

  /**
   * Convert the instance into URL query string.
   *
   * @return URL query string
   */
  public String toUrlQueryString() {
    return toUrlQueryString(null);
  }

  /**
   * Convert the instance into URL query string.
   *
   * @param prefix prefix of the query string
   * @return URL query string
   */
  public String toUrlQueryString(String prefix) {
    String suffix = "";
    String containerSuffix = "";
    String containerPrefix = "";
    if (prefix == null) {
      // style=form, explode=true, e.g. /pet?name=cat&type=manx
      prefix = "";
    } else {
      // deepObject style e.g. /pet?id[name]=cat&id[type]=manx
      prefix = prefix + "[";
      suffix = "]";
      containerSuffix = "]";
      containerPrefix = "[";
    }

    StringJoiner joiner = new StringJoiner("&");

    // add `linkedSum` to the URL query string
    if (getLinkedSum() != null) {
      try {
        joiner.add(String.format(java.util.Locale.ROOT, "%slinkedSum%s=%s", prefix, suffix, URLEncoder.encode(String.valueOf(getLinkedSum()), "UTF-8").replaceAll("\\+", "%20")));
      } catch (UnsupportedEncodingException e) {
        // Should never happen, UTF-8 is always supported
        throw new RuntimeException(e);
      }
    }

    return joiner.toString();
  }

}
